#!/usr/bin/env python3

import bpy
import random
import math
import json
import os
import sys
import subprocess
import types
from mathutils import Vector
from bpy_extras.object_utils import world_to_camera_view

PROJECT_ROOT = os.environ.get("PROJECT_ROOT", os.path.expanduser('~/SpatialAct'))
sys.path.insert(0, PROJECT_ROOT)
sys.path.insert(0, os.path.join(PROJECT_ROOT, 'src'))
sys.path.insert(0, os.path.join(PROJECT_ROOT, 'blender_scripts'))

from src.building_labels import BuildingLabeler, is_building as check_is_building, is_road, apply_road_material, is_visible_object

# ============================================================
# Configuration
# ============================================================
import argparse

parser = argparse.ArgumentParser(description="Generate region mental-rotation task data")
parser.add_argument("--region", type=str, default=None, help="Region name, e.g., region_a, region_b")
parser.add_argument("--max-regions", type=int, default=None, help="Maximum number of regions to process; <=0 means all")
parser.add_argument(
    "--use-clean",
    type=int,
    default=1,
    help="Prefer clean outputs generated by preprocess_clean.py (1=yes, 0=no)",
)
args, _ = parser.parse_known_args()

REGION_NAME = args.region if args.region else os.environ.get("REGION_NAME", "region")
MAX_REGIONS_ARG = args.max_regions
USE_CLEAN_ARG = int(args.use_clean)
BLEND_PATH = os.environ.get("BLEND_PATH", os.path.join(PROJECT_ROOT, f"{REGION_NAME}_osm_scene_0228/osm_reference.blend"))
REGION_DIR = os.environ.get("REGION_DIR", os.path.join(PROJECT_ROOT, f"benchmark/data_construct/model_process/results/{REGION_NAME}_kmeans"))
OUTPUT_ROOT = os.environ.get("OUTPUT_ROOT", os.path.join(PROJECT_ROOT, "benchmark/data/mental_rotation"))
OUTPUT_DIR = os.path.join(OUTPUT_ROOT, f"{REGION_NAME}_regions")

RESOLUTION = int(os.environ.get("RESOLUTION", "0"))
MAX_BUILDINGS_PER_REGION = int(os.environ.get("MAX_BUILDINGS_PER_REGION", "15"))

# Mental-rotation parameters
ROT_MCQ_K = 4
ROT_IMG_MCQ_K = 4
ROT_ANGLE_POOL = [30, 45, 60, 90, 120, 135, 150, 180, 210, 225, 240, 270, 300, 315, 330]
ROT_DIR_POOL = ["cw", "ccw"]

COLLISION_PAD = 0.12
MIN_GAP = 1.0
LABEL_COLOR = (0.02, 0.02, 0.02, 1.0)
WHITE_FILM_ALPHA = 0.92
TOP_FIT_MARGIN_RATIO = 0.26
ISO_FIT_MARGIN_RATIO = 0.32
MIN_FIT_ORTHO_SCALE = 2.2
TOP_NORTH_ARROW_SIZE = 96
ISO_NORTH_ARROW_SIZE = 104
SHOW_ROADS_IN_REGION_RENDER = os.environ.get("SHOW_ROADS_IN_REGION_RENDER", "1").lower() in ("1", "true", "yes")
REFRAME_PAD_RATIO = float(os.environ.get("REFRAME_PAD_RATIO", "0.45"))
REFRAME_CONTENT_FILL_RATIO = float(os.environ.get("REFRAME_CONTENT_FILL_RATIO", "1.00"))
FINAL_TRIM_PAD_PX = int(os.environ.get("FINAL_TRIM_PAD_PX", "180"))
TASK3_DYNAMIC_POST_CROP = os.environ.get("TASK3_DYNAMIC_POST_CROP", "0").lower() in ("1", "true", "yes")
# Global view scale for the whole task3 pipeline (all QA types in the same region share the same enlarged FOV).
TASK3_GLOBAL_VIEW_MARGIN_SCALE = float(
    os.environ.get("TASK3_GLOBAL_VIEW_MARGIN_SCALE", os.environ.get("REGION_ROTATION_VIEW_MARGIN_SCALE", "1.20"))
)


def force_disable_all_shadows():
    scene = bpy.context.scene
    scene.cycles.use_shadows = False
    scene.cycles.use_progressive = False
    scene.cycles.use_shadow_highlight = False
    scene.cycles.blur_shadow = 0

    if hasattr(scene.cycles, 'shader_cache'):
        scene.cycles.shader_cache = 0

    for obj in bpy.data.objects:
        if obj.type == 'LIGHT':
            if hasattr(obj.data, 'shadow_ray_visibility'):
                obj.data.shadow_ray_visibility = {'CAST_SHADOWS': False}
            if hasattr(obj.data, 'cast_shadow'):
                obj.data.cast_shadow = False

    for obj in bpy.data.objects:
        if hasattr(obj, 'cycles_visibility'):
            obj.cycles_visibility.cast_shadow = False
            obj.cycles_visibility.receive_shadow = False

    for obj in bpy.data.objects:
        if check_is_building(obj.name):
            if hasattr(obj, 'cycles_visibility'):
                obj.cycles_visibility.cast_shadow = False
                obj.cycles_visibility.receive_shadow = False

    for obj in bpy.data.objects:
        if obj.name.startswith('Label_'):
            if hasattr(obj, 'cycles_visibility'):
                obj.cycles_visibility.cast_shadow = False
                obj.cycles_visibility.receive_shadow = False
                obj.cycles_visibility.glossy = False
                obj.cycles_visibility.scatter = False
                obj.cycles_visibility.shadow = False
            try:
                obj.visible_shadow = False
            except:
                pass

    if "World" in bpy.data.worlds:
        world = bpy.data.worlds["World"]
        world.use_nodes = True
        nodes = world.node_tree.nodes
        links = world.node_tree.links
        nodes.clear()
        links.clear()
        output = nodes.new('ShaderNodeOutputWorld')
        bg = nodes.new('ShaderNodeBackground')
        bg.inputs['Color'].default_value = (1.0, 1.0, 1.0, 1.0)
        bg.inputs['Strength'].default_value = 0.0
        links.new(bg.outputs['Background'], output.inputs['Surface'])


def _compute_north_screen_vec(cam, north_world_dir: Vector) -> Vector:
    m = cam.matrix_world.to_3x3()
    cam_right = (m @ Vector((1.0, 0.0, 0.0))).normalized()
    cam_up = (m @ Vector((0.0, 1.0, 0.0))).normalized()
    d = north_world_dir.normalized()
    screen_vec = Vector((d.dot(cam_right), -d.dot(cam_up)))
    if screen_vec.length < 1e-6:
        return Vector((0.0, -1.0))
    screen_vec.normalize()
    return screen_vec


def _draw_north_arrow_via_system_python(
    image_path: str,
    screen_vec: Vector,
    arrow_color=(255, 0, 0, 255),
    arrow_size=120,
    corner_idx: int | None = None,
) -> dict | None:
    payload = {
        "image_path": image_path,
        "screen_vec": [float(screen_vec.x), float(screen_vec.y)],
        "arrow_color": [int(arrow_color[0]), int(arrow_color[1]), int(arrow_color[2]), int(arrow_color[3])],
        "arrow_size": int(arrow_size),
        "corner_idx": (int(corner_idx) if corner_idx is not None else None),
    }
    helper_script = r"""
import json, os, sys
from PIL import Image, ImageDraw, ImageFont

def load_font(sz):
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf",
    ]
    for fp in candidates:
        if os.path.exists(fp):
            try:
                return ImageFont.truetype(fp, sz)
            except Exception:
                continue
    return ImageFont.load_default()

def norm2(x, y):
    n = (x * x + y * y) ** 0.5
    if n < 1e-8:
        return 0.0, -1.0
    return x / n, y / n

payload = json.loads(sys.argv[1])
image_path = payload["image_path"]
if not os.path.exists(image_path):
    raise SystemExit(0)
sv = payload.get("screen_vec", [0.0, -1.0])
vx, vy = norm2(float(sv[0]), float(sv[1]))
arrow_color = tuple(int(v) for v in payload.get("arrow_color", [255, 0, 0, 255]))
arrow_size = int(payload.get("arrow_size", 120))

img = Image.open(image_path).convert("RGBA")
draw = ImageDraw.Draw(img)
width, height = img.size
base_w, base_h = width, height
alpha = img.getchannel("A")
pix = img.load()
ext_top = 0
ext_right = 0
expanded = False

margin = max(16, int(arrow_size * 0.20))
panel_w = int(arrow_size * 1.75)
panel_h = int(arrow_size * 1.95)
candidates = [
    (width - margin - panel_w, margin),
    (margin, margin),
    (width - margin - panel_w, height - margin - panel_h),
    (margin, height - margin - panel_h),
]
corner_idx = payload.get("corner_idx", None)

def overlap_ratio(px, py):
    x1 = max(0, int(px)); y1 = max(0, int(py))
    x2 = min(width, x1 + panel_w); y2 = min(height, y1 + panel_h)
    if x2 <= x1 or y2 <= y1:
        return 1.0
    patch = alpha.crop((x1, y1, x2, y2))
    hist = patch.histogram()
    non_transparent = (x2 - x1) * (y2 - y1) - hist[0]
    return non_transparent / float((x2 - x1) * (y2 - y1))

def is_building_pixel(r, g, b, a):
    if a <= 0:
        return False
    # Ignore common road-yellow pixels to avoid treating roads as buildings
    is_yellow_road = (r > 150 and g > 150 and b < 120 and abs(r - g) < 80)
    return (not is_yellow_road)

def panel_overlaps_buildings(px, py):
    x1 = max(0, int(px))
    y1 = max(0, int(py))
    x2 = min(width, x1 + panel_w)
    y2 = min(height, y1 + panel_h)
    if x2 <= x1 or y2 <= y1:
        return False
    for yy in range(y1, y2):
        for xx in range(x1, x2):
            r, g, b, a = pix[xx, yy]
            if is_building_pixel(r, g, b, a):
                return True
    return False

if isinstance(corner_idx, int) and 0 <= corner_idx < len(candidates):
    bx, by = candidates[corner_idx]
else:
    bx, by = min(candidates, key=lambda xy: overlap_ratio(xy[0], xy[1]))

x1, y1 = int(bx), int(by)
x2, y2 = x1 + panel_w, y1 + panel_h


old_w, old_h = width, height
ext_w = panel_w + 2 * margin
ext_top = 0
new_w = old_w + ext_w
new_h = old_h + ext_top
ext_right = ext_w
expanded = True

new_img = Image.new("RGBA", (new_w, new_h), (0, 0, 0, 0))
new_img.paste(img, (0, ext_top), img)
img = new_img
draw = ImageDraw.Draw(img)
pix = img.load()
width, height = img.size

x1 = old_w + max(0, (ext_w - panel_w) // 2)
y1 = margin

x2, y2 = x1 + panel_w, y1 + panel_h
draw.rectangle([x1, y1, x2, y2], fill=(0, 0, 0, 220))

cx = x1 + panel_w * 0.63
cy = y1 + panel_h * 0.40
arrow_len = arrow_size * 0.52
head = arrow_size * 0.20
shaft_w = max(3, int(arrow_size * 0.05))
px, py = -vy, vx

tip = (cx + vx * arrow_len * 0.5, cy + vy * arrow_len * 0.5)
bottom = (cx - vx * arrow_len * 0.5, cy - vy * arrow_len * 0.5)
wing_base = (tip[0] - vx * head, tip[1] - vy * head)
left_wing = (wing_base[0] + px * head * 0.58, wing_base[1] + py * head * 0.58)
right_wing = (wing_base[0] - px * head * 0.58, wing_base[1] - py * head * 0.58)

draw.line([bottom, tip], fill=arrow_color, width=shaft_w)
draw.polygon([tip, left_wing, right_wing], fill=arrow_color)
font = load_font(max(16, int(arrow_size * 0.34)))
draw.text((x1 + panel_w * 0.20, y1 + panel_h * 0.60), "N", fill=arrow_color, font=font)
img.save(image_path)
print(json.dumps({
    "ok": True,
    "expanded": bool(expanded),
    "ext_top": int(ext_top),
    "ext_right": int(ext_right),
    "base_w": int(base_w),
    "base_h": int(base_h),
    "final_w": int(width),
    "final_h": int(height),
}))
"""
    try:
        cp = subprocess.run(
            ["python3", "-c", helper_script, json.dumps(payload, ensure_ascii=False)],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        meta = None
        for line in reversed(cp.stdout.splitlines()):
            line = line.strip()
            if not line:
                continue
            try:
                parsed = json.loads(line)
                if isinstance(parsed, dict):
                    meta = parsed
                    break
            except Exception:
                continue
        if meta is None:
            meta = {"ok": True, "expanded": False, "ext_top": 0, "ext_right": 0}
        return meta
    except Exception as e:
        print(f"  [draw_north_arrow] Warning: external python fallback failed: {e}")
        return None


def draw_north_arrow(
    image_path: str,
    cam,
    north_world_dir=None,
    arrow_color=(255, 0, 0, 255),
    arrow_size=120,
    corner_idx: int | None = 0,
    return_meta: bool = False,
):
    if not os.path.exists(image_path):
        if return_meta:
            return None
        return image_path
    if north_world_dir is None:
        north_world_dir = Vector((0.0, 1.0, 0.0))
    screen_vec = _compute_north_screen_vec(cam, north_world_dir)
    meta = _draw_north_arrow_via_system_python(
        image_path,
        screen_vec,
        arrow_color=arrow_color,
        arrow_size=arrow_size,
        corner_idx=corner_idx,
    )
    if return_meta:
        return meta
    return image_path


def reframe_image_focus_buildings(
    image_path: str,
    pad_ratio: float | None = None,
    content_fill_ratio: float | None = None,
    arrow_size: int | None = None,
    reserve_for_north: bool = True,
    building_bbox: tuple[int, int, int, int] | None = None,
) -> bool:
    if not os.path.exists(image_path):
        return False
    if pad_ratio is None:
        pad_ratio = REFRAME_PAD_RATIO
    if content_fill_ratio is None:
        content_fill_ratio = REFRAME_CONTENT_FILL_RATIO
    payload = {
        "image_path": image_path,
        "pad_ratio": float(max(0.0, min(0.5, pad_ratio))),
        "content_fill_ratio": float(max(0.35, min(1.0, content_fill_ratio))),
        "arrow_size": (int(arrow_size) if arrow_size is not None else None),
        "reserve_for_north": bool(reserve_for_north),
        "building_bbox": (
            [int(building_bbox[0]), int(building_bbox[1]), int(building_bbox[2]), int(building_bbox[3])]
            if building_bbox is not None else None
        ),
    }
    helper_script = r"""
import json, os, sys
from PIL import Image

payload = json.loads(sys.argv[1])
image_path = payload["image_path"]
if not os.path.exists(image_path):
    raise SystemExit(0)

pad_ratio = float(payload.get("pad_ratio", 0.20))
bbox = payload.get("building_bbox", None)

img = Image.open(image_path).convert("RGBA")
w, h = img.size
pix = img.load()

if isinstance(bbox, list) and len(bbox) == 4:
    x1, y1, x2, y2 = [int(v) for v in bbox]
    x1 = max(0, min(w - 1, x1)); y1 = max(0, min(h - 1, y1))
    x2 = max(0, min(w - 1, x2)); y2 = max(0, min(h - 1, y2))
    if x2 < x1: x1, x2 = x2, x1
    if y2 < y1: y1, y2 = y2, y1
else:
    xs, ys = [], []
    for y in range(h):
        for x in range(w):
            r, g, b, a = pix[x, y]
            if a <= 0:
                continue
            if (r > 140 and g > 140 and b > 140) and (abs(r - g) < 45 and abs(r - b) < 45 and abs(g - b) < 45):
                xs.append(x); ys.append(y)
    if not xs or not ys:
        for y in range(h):
            for x in range(w):
                if pix[x, y][3] > 0:
                    xs.append(x); ys.append(y)
    if not xs or not ys:
        raise SystemExit(0)
    x1, x2 = min(xs), max(xs)
    y1, y2 = min(ys), max(ys)

bw = max(1, x2 - x1 + 1); bh = max(1, y2 - y1 + 1)
pad_x = int(round(bw * pad_ratio)); pad_y = int(round(bh * pad_ratio))
x1 = max(0, x1 - pad_x); y1 = max(0, y1 - pad_y)
x2 = min(w - 1, x2 + pad_x); y2 = min(h - 1, y2 + pad_y)
crop = img.crop((x1, y1, x2 + 1, y2 + 1))
cw, ch = crop.size

if cw <= 0 or ch <= 0:
    raise SystemExit(0)
crop.save(image_path)
"""
    try:
        subprocess.run(
            ["python3", "-c", helper_script, json.dumps(payload, ensure_ascii=False)],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        return True
    except Exception as e:
        print(f"  [reframe] Warning: reframing failed for {image_path}: {e}")
        return False


def trim_image_to_alpha_bbox(image_path: str, pad_px: int = 0, return_meta: bool = False):
    if not os.path.exists(image_path):
        return None if return_meta else False
    payload = {
        "image_path": image_path,
        "pad_px": int(max(0, pad_px)),
    }
    helper_script = r"""
import json, os, sys
from PIL import Image

payload = json.loads(sys.argv[1])
image_path = payload["image_path"]
pad = int(payload.get("pad_px", 0))
if not os.path.exists(image_path):
    raise SystemExit(0)

img = Image.open(image_path).convert("RGBA")
w, h = img.size
x1 = y1 = x2 = y2 = None
pix = img.load()
for y in range(h):
    for x in range(w):
        r, g, b, a = pix[x, y]
        if a <= 0:
            continue
        # Ignore common yellow road pixels so roads do not over-expand the crop box
        is_yellow_road = (r > 150 and g > 150 and b < 120 and abs(r - g) < 80)
        if is_yellow_road:
            continue
        if x1 is None:
            x1 = x2 = x
            y1 = y2 = y
        else:
            if x < x1: x1 = x
            if y < y1: y1 = y
            if x > x2: x2 = x
            if y > y2: y2 = y

if x1 is None:
    alpha = img.getchannel("A")
    bbox = alpha.getbbox()
    if bbox is None:
        raise SystemExit(0)
    x1, y1, x2, y2 = bbox
else:
    x2 += 1
    y2 += 1

x1 = max(0, x1 - pad)
y1 = max(0, y1 - pad)
x2 = min(w, x2 + pad)
y2 = min(h, y2 + pad)
if x2 <= x1 or y2 <= y1:
    raise SystemExit(0)
out = img.crop((x1, y1, x2, y2))
out.save(image_path)
print(json.dumps({
    "ok": True,
    "crop_x1": int(x1),
    "crop_y1": int(y1),
    "crop_x2": int(x2),
    "crop_y2": int(y2),
    "final_w": int(out.size[0]),
    "final_h": int(out.size[1]),
}))
"""
    try:
        cp = subprocess.run(
            ["python3", "-c", helper_script, json.dumps(payload, ensure_ascii=False)],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        meta = None
        for line in reversed(cp.stdout.splitlines()):
            line = line.strip()
            if not line:
                continue
            try:
                parsed = json.loads(line)
                if isinstance(parsed, dict):
                    meta = parsed
                    break
            except Exception:
                continue
        if return_meta:
            return meta
        return (meta is not None)
    except Exception as e:
        print(f"  [trim] Warning: trim failed for {image_path}: {e}")
        return None if return_meta else False


def _iter_object_world_vertices(obj):
    if obj is None or obj.type != "MESH":
        return
    mesh = obj.data
    if not mesh.vertices:
        return
    used = set()
    for poly in mesh.polygons:
        for vid in poly.vertices:
            used.add(int(vid))
    if used:
        for vid in used:
            yield obj.matrix_world @ mesh.vertices[vid].co
    else:
        for v in mesh.vertices:
            yield obj.matrix_world @ v.co


def _render_resolution_px() -> tuple[int, int]:
    scene = bpy.context.scene
    rx = int(scene.render.resolution_x * scene.render.resolution_percentage / 100.0)
    ry = int(scene.render.resolution_y * scene.render.resolution_percentage / 100.0)
    return max(1, rx), max(1, ry)


def fit_ortho_camera_to_objects(cam, objects: list, margin_ratio: float = 0.08, min_ortho_scale: float = 2.2) -> None:
    if cam is None or cam.type != "CAMERA" or cam.data.type != "ORTHO":
        return
    world_points = []
    for obj in objects:
        for p in _iter_object_world_vertices(obj):
            world_points.append(p)
    if not world_points:
        return
    cam_axes = cam.matrix_world.to_3x3()
    cam_right = (cam_axes @ Vector((1.0, 0.0, 0.0))).normalized()
    cam_up = (cam_axes @ Vector((0.0, 1.0, 0.0))).normalized()
    top_like = (
        abs(cam_right.z) < 1e-5 and abs(cam_up.z) < 1e-5 and
        abs(abs(cam_right.x) - 1.0) < 1e-3 and abs(abs(cam_up.y) - 1.0) < 1e-3
    )
    if top_like:
        wx = [float(p.x) for p in world_points]
        wy = [float(p.y) for p in world_points]
        cam.location.x = 0.5 * (min(wx) + max(wx))
        cam.location.y = 0.5 * (min(wy) + max(wy))
        bpy.context.view_layer.update()
        fit_half_x = 0.5 * (max(wx) - min(wx))
        fit_half_y = 0.5 * (max(wy) - min(wy))
        rx, ry = _render_resolution_px()
        aspect = float(rx) / float(max(1, ry))
        needed_scale = max(2.0 * fit_half_x, 2.0 * fit_half_y * aspect)
        cam.data.ortho_scale = max(min_ortho_scale, needed_scale * (1.0 + margin_ratio))
        return
    cam_inv = cam.matrix_world.inverted()
    xs = []
    ys = []
    for p in world_points:
        q = cam_inv @ p
        xs.append(float(q.x))
        ys.append(float(q.y))
    cx = 0.5 * (min(xs) + max(xs))
    cy = 0.5 * (min(ys) + max(ys))
    cam.location = cam.location + cam_right * cx + cam_up * cy
    bpy.context.view_layer.update()
    cam_inv = cam.matrix_world.inverted()
    xs = []
    ys = []
    for p in world_points:
        q = cam_inv @ p
        xs.append(float(q.x))
        ys.append(float(q.y))
    fit_half_x = max(abs(min(xs)), abs(max(xs)))
    fit_half_y = max(abs(min(ys)), abs(max(ys)))
    rx, ry = _render_resolution_px()
    aspect = float(rx) / float(max(1, ry))
    needed_scale = max(2.0 * fit_half_x, 2.0 * fit_half_y * aspect)
    cam.data.ortho_scale = max(min_ortho_scale, needed_scale * (1.0 + margin_ratio))


def create_white_film_material(name: str = "Mask_WhiteFilm") -> bpy.types.Material:
    if name in bpy.data.materials:
        return bpy.data.materials[name]
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    mat.blend_method = "BLEND" if WHITE_FILM_ALPHA < 0.995 else "OPAQUE"
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()
    output = nodes.new("ShaderNodeOutputMaterial")
    emission = nodes.new("ShaderNodeEmission")
    emission.inputs["Color"].default_value = (1.0, 1.0, 1.0, 1.0)
    emission.inputs["Strength"].default_value = 1.0
    if WHITE_FILM_ALPHA < 0.995:
        transparent = nodes.new("ShaderNodeBsdfTransparent")
        mix = nodes.new("ShaderNodeMixShader")
        mix.inputs["Fac"].default_value = WHITE_FILM_ALPHA
        links.new(transparent.outputs["BSDF"], mix.inputs[1])
        links.new(emission.outputs["Emission"], mix.inputs[2])
        links.new(mix.outputs["Shader"], output.inputs["Surface"])
    else:
        links.new(emission.outputs["Emission"], output.inputs["Surface"])
    return mat


def apply_white_film_to_buildings(building_ids: list[str]) -> None:
    mat = create_white_film_material()
    for building_id in building_ids:
        obj = bpy.data.objects.get(building_id)
        if not obj or obj.type != "MESH":
            continue
        obj.data.materials.clear()
        obj.data.materials.append(mat)
        obj.visible_shadow = False
        if hasattr(obj, "cycles_visibility"):
            obj.cycles_visibility.shadow = False


def create_black_label_material(name: str = "Label_Black_Mat") -> bpy.types.Material:
    if name in bpy.data.materials:
        return bpy.data.materials[name]
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()
    output = nodes.new("ShaderNodeOutputMaterial")
    bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    bsdf.inputs["Base Color"].default_value = LABEL_COLOR
    bsdf.inputs["Roughness"].default_value = 0.25
    bsdf.inputs["Specular"].default_value = 0.28
    links.new(bsdf.outputs["BSDF"], output.inputs["Surface"])
    return mat


def set_all_labels_black() -> None:
    label_mat = create_black_label_material()
    for obj in bpy.data.objects:
        if obj.type == "FONT" and obj.name.startswith("Label_"):
            obj.data.materials.clear()
            obj.data.materials.append(label_mat)
            obj.visible_shadow = False
            if hasattr(obj, "cycles_visibility"):
                obj.cycles_visibility.shadow = False
                obj.cycles_visibility.diffuse = False
                obj.cycles_visibility.glossy = False
                obj.cycles_visibility.ambient_occlusion = False


def get_region_building_objects(building_ids: list[str]) -> list:
    objs = []
    for building_id in building_ids:
        obj = bpy.data.objects.get(building_id)
        if obj and obj.type == "MESH":
            objs.append(obj)
    return objs


def set_road_visibility(visible: bool) -> None:
    for obj in bpy.data.objects:
        if obj.type != "MESH":
            continue
        if not is_road(obj.name):
            continue
        obj.hide_set(not visible)
        obj.hide_render = (not visible)


def projected_building_bbox_pixels(cam, objects: list) -> tuple[int, int, int, int] | None:
    if cam is None or cam.type != "CAMERA":
        return None
    scene = bpy.context.scene
    rx, ry = _render_resolution_px()
    xs = []
    ys = []
    for obj in objects:
        for p in _iter_object_world_vertices(obj):
            ndc = world_to_camera_view(scene, cam, p)
            x = float(ndc.x) * rx
            y = (1.0 - float(ndc.y)) * ry
            xs.append(x)
            ys.append(y)
    if not xs or not ys:
        return None
    x1 = max(0, min(rx - 1, int(math.floor(min(xs)))))
    y1 = max(0, min(ry - 1, int(math.floor(min(ys)))))
    x2 = max(0, min(rx - 1, int(math.ceil(max(xs)))))
    y2 = max(0, min(ry - 1, int(math.ceil(max(ys)))))
    if x2 <= x1 or y2 <= y1:
        return None
    return (x1, y1, x2, y2)


def _compute_reframe_crop_bounds_from_bbox(
    image_w: int,
    image_h: int,
    building_bbox: tuple[int, int, int, int] | None,
    pad_ratio: float,
) -> tuple[int, int, int, int]:
    if building_bbox is None:
        return (0, 0, int(image_w), int(image_h))

    x1 = max(0, min(image_w - 1, int(building_bbox[0])))
    y1 = max(0, min(image_h - 1, int(building_bbox[1])))
    x2 = max(0, min(image_w - 1, int(building_bbox[2])))
    y2 = max(0, min(image_h - 1, int(building_bbox[3])))
    if x2 < x1:
        x1, x2 = x2, x1
    if y2 < y1:
        y1, y2 = y2, y1

    bw = max(1, x2 - x1 + 1)
    bh = max(1, y2 - y1 + 1)
    pad_x = int(round(bw * float(pad_ratio)))
    pad_y = int(round(bh * float(pad_ratio)))

    x1 = max(0, x1 - pad_x)
    y1 = max(0, y1 - pad_y)
    x2 = min(image_w - 1, x2 + pad_x)
    y2 = min(image_h - 1, y2 + pad_y)
    return (int(x1), int(y1), int(x2 + 1), int(y2 + 1))


def _pixel_to_world_xy_in_top(cam, px: float, py: float, rx: int, ry: int) -> tuple[float, float]:
    cam_axes = cam.matrix_world.to_3x3()
    cam_right = (cam_axes @ Vector((1.0, 0.0, 0.0))).normalized()
    cam_up = (cam_axes @ Vector((0.0, 1.0, 0.0))).normalized()
    world_per_px = float(cam.data.ortho_scale) / float(max(1, rx))
    dx = (float(px) - float(rx) * 0.5) * world_per_px
    dy = (float(ry) * 0.5 - float(py)) * world_per_px
    wp = cam.location + cam_right * dx + cam_up * dy
    return float(wp.x), float(wp.y)


def _compute_top_center_world_from_render_meta(cam, render_meta: dict | None) -> dict | None:
    if not isinstance(render_meta, dict):
        return None
    reframe_crop = render_meta.get("reframe_crop")
    north_meta = render_meta.get("north_meta") or {}
    trim_meta = render_meta.get("trim_meta") or {}
    rx = int(render_meta.get("render_w", 0))
    ry = int(render_meta.get("render_h", 0))
    if not (isinstance(reframe_crop, (list, tuple)) and len(reframe_crop) == 4):
        return None
    if not isinstance(trim_meta, dict):
        return None

    final_w = float(trim_meta.get("final_w", 0.0))
    final_h = float(trim_meta.get("final_h", 0.0))
    if final_w <= 0 or final_h <= 0 or rx <= 0 or ry <= 0:
        return None

    final_cx = final_w * 0.5
    final_cy = final_h * 0.5
    reframe_x1, reframe_y1 = int(reframe_crop[0]), int(reframe_crop[1])
    trim_x1 = int(trim_meta.get("crop_x1", 0))
    trim_y1 = int(trim_meta.get("crop_y1", 0))
    ext_top = int(north_meta.get("ext_top", 0))

    render_cx = float(final_cx) + float(trim_x1) + float(reframe_x1)
    render_cy = float(final_cy) + float(trim_y1) - float(ext_top) + float(reframe_y1)
    world_cx, world_cy = _pixel_to_world_xy_in_top(cam, render_cx, render_cy, rx, ry)

    return {
        "center_final_px": (float(final_cx), float(final_cy)),
        "center_render_px": (float(render_cx), float(render_cy)),
        "center_world_xy": (float(world_cx), float(world_cy)),
    }


def load_buildings_from_blend(blend_file: str) -> list:
    blender_script = """
import bpy
import json
from mathutils import Vector

buildings = []
for obj in bpy.data.objects:
    if obj.type != 'MESH':
        continue
    if 'osm_buildings' not in obj.name:
        continue

    world_matrix = obj.matrix_world
    mesh = obj.data
    if not mesh:
        continue

    vertices = []
    for v in mesh.vertices:
        world_co = world_matrix @ v.co
        vertices.append([world_co.x, world_co.y, world_co.z])

    if not vertices:
        continue

    xs = [v[0] for v in vertices]
    ys = [v[1] for v in vertices]
    zs = [v[2] for v in vertices]

    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    min_z, max_z = min(zs), max(zs)

    center_x = (min_x + max_x) / 2
    center_y = (min_y + max_y) / 2
    center_z = (min_z + max_z) / 2
    width = max_x - min_x
    depth = max_y - min_y
    height = max_z - min_z

    buildings.append({
        "id": obj.name,
        "center": [center_x, center_y, center_z],
        "min": [min_x, min_y, min_z],
        "max": [max_x, max_y, max_z],
        "width": width,
        "depth": depth,
        "height": height,
        "half_w": width / 2,
        "half_d": depth / 2,
    })

print(f"JSON_DATA:{json.dumps(buildings)}")
"""
    import subprocess
    result = subprocess.run(
        ['blender', '-b', blend_file, '--python-expr', blender_script],
        capture_output=True, text=True, timeout=60
    )

    output = result.stdout + result.stderr
    if "JSON_DATA:" in output:
        json_str = output.split("JSON_DATA:")[1].strip()
        start = json_str.find('[')
        end = json_str.rfind(']') + 1
        if start >= 0 and end > start:
            json_str = json_str[start:end]
            return json.loads(json_str)
    return []


def load_region_data(region_file_or_dir: str) -> dict:
    if os.path.isdir(region_file_or_dir):
        region_file = os.path.join(region_file_or_dir, "region_data.json")
    else:
        region_file = region_file_or_dir
    with open(region_file, 'r') as f:
        return json.load(f)


def _load_failed_region_ids(failed_regions_path: str) -> set[int]:
    if not os.path.exists(failed_regions_path):
        return set()
    try:
        with open(failed_regions_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, list):
            return {int(x) for x in data}
    except Exception as e:
        print(f"[WARN] Failed to read failed_regions: {failed_regions_path}, err={e}")
    return set()


def resolve_region_inputs(blend_path: str, region_dir: str, use_clean: bool) -> tuple[str, str, set[int], bool]:
    clean_blend_path = os.environ.get("CLEAN_BLEND_PATH", blend_path.replace(".blend", "_clean.blend"))
    clean_region_json_path = os.environ.get("CLEAN_REGION_JSON_PATH", os.path.join(region_dir, "region_data_clean.json"))
    raw_region_json_path = os.path.join(region_dir, "region_data.json")
    failed_regions_path = os.environ.get("FAILED_REGIONS_PATH", os.path.join(region_dir, "failed_regions.json"))

    failed_region_ids = _load_failed_region_ids(failed_regions_path)

    if use_clean and os.path.exists(clean_blend_path) and os.path.exists(clean_region_json_path):
        return clean_blend_path, clean_region_json_path, failed_region_ids, True

    if use_clean:
        missing = []
        if not os.path.exists(clean_blend_path):
            missing.append(clean_blend_path)
        if not os.path.exists(clean_region_json_path):
            missing.append(clean_region_json_path)
        print("[WARN] Incomplete clean inputs; falling back to raw scene. Missing files:")
        for p in missing:
            print(f"       - {p}")

    return blend_path, raw_region_json_path, failed_region_ids, False


def get_buildings_in_region(all_buildings: list, building_ids: list) -> list:
    id_set = set(building_ids)
    return [b for b in all_buildings if b['id'] in id_set]


# ============================================================
# Collision detection (same as task4: AABB prefilter + OBB(SAT) precise test)
# ============================================================

def _object_world_xy_bounds(obj) -> tuple[float, float, float, float] | None:
    if obj is None or obj.type != "MESH":
        return None
    if hasattr(obj, "bound_box") and obj.bound_box:
        verts = [obj.matrix_world @ Vector(co) for co in obj.bound_box]
    else:
        verts = [obj.matrix_world @ v.co for v in obj.data.vertices]
    if not verts:
        return None
    xs = [float(v.x) for v in verts]
    ys = [float(v.y) for v in verts]
    return (min(xs), max(xs), min(ys), max(ys))


def compute_pca_obb_xy(world_xy_pts: list[tuple[float, float]]) -> dict | None:
    if not world_xy_pts:
        return None
    n = len(world_xy_pts)
    mx = sum(p[0] for p in world_xy_pts) / n
    my = sum(p[1] for p in world_xy_pts) / n
    xx = sum((p[0] - mx) ** 2 for p in world_xy_pts)
    yy = sum((p[1] - my) ** 2 for p in world_xy_pts)
    xy = sum((p[0] - mx) * (p[1] - my) for p in world_xy_pts)

    if abs(xy) < 1e-9:
        angle = 0.0 if xx >= yy else (math.pi / 2.0)
    else:
        angle = 0.5 * math.atan2(2.0 * xy, xx - yy)

    ca = math.cos(angle)
    sa = math.sin(angle)
    ax = (ca, sa)
    ay = (-sa, ca)

    rot = []
    for (x, y) in world_xy_pts:
        dx = x - mx
        dy = y - my
        rx = ca * dx + sa * dy
        ry = -sa * dx + ca * dy
        rot.append((rx, ry))

    rxs = [p[0] for p in rot]
    rys = [p[1] for p in rot]
    min_rx, max_rx = min(rxs), max(rxs)
    min_ry, max_ry = min(rys), max(rys)

    hx = 0.5 * (max_rx - min_rx)
    hy = 0.5 * (max_ry - min_ry)
    crx = 0.5 * (min_rx + max_rx)
    cry = 0.5 * (min_ry + max_ry)
    cx = mx + ca * crx - sa * cry
    cy = my + sa * crx + ca * cry

    return {
        "angle": float(angle),
        "ax": (float(ax[0]), float(ax[1])),
        "ay": (float(ay[0]), float(ay[1])),
        "hx": float(hx),
        "hy": float(hy),
        "center": (float(cx), float(cy)),
    }


def build_collision_meta_from_obj(obj: bpy.types.Object) -> dict | None:
    b = _object_world_xy_bounds(obj)
    if b is None:
        return None
    min_x, max_x, min_y, max_y = b
    half_w = 0.5 * float(max_x - min_x)
    half_d = 0.5 * float(max_y - min_y)

    verts = obj.data.vertices if obj and obj.type == "MESH" and obj.data else []
    pts = []
    step = max(1, len(verts) // 500) if verts else 1
    for i in range(0, len(verts), step):
        w = obj.matrix_world @ verts[i].co
        pts.append((float(w.x), float(w.y)))

    obb = compute_pca_obb_xy(pts)
    if obb is None:
        obb = {
            "angle": 0.0,
            "ax": (1.0, 0.0),
            "ay": (0.0, 1.0),
            "hx": half_w,
            "hy": half_d,
            "center": (float((min_x + max_x) * 0.5), float((min_y + max_y) * 0.5)),
        }

    return {
        "half_w": float(half_w),
        "half_d": float(half_d),
        "obb": obb,
    }


def aabb_overlap_xy_by_meta(ma: dict, mb: dict, inflate: float = 0.0) -> bool:
    ax, ay = tuple(ma["obb"]["center"][:2])
    bx, by = tuple(mb["obb"]["center"][:2])
    inf = float(inflate)

    min_ax = ax - ma["half_w"] - inf
    max_ax = ax + ma["half_w"] + inf
    min_ay = ay - ma["half_d"] - inf
    max_ay = ay + ma["half_d"] + inf

    min_bx = bx - mb["half_w"] - inf
    max_bx = bx + mb["half_w"] + inf
    min_by = by - mb["half_d"] - inf
    max_by = by + mb["half_d"] + inf

    if max_ax < min_bx or min_ax > max_bx:
        return False
    if max_ay < min_by or min_ay > max_by:
        return False
    return True


def _normalize2(v: tuple[float, float]) -> tuple[float, float]:
    l = math.hypot(v[0], v[1])
    if l < 1e-9:
        return (1.0, 0.0)
    return (v[0] / l, v[1] / l)


def _project_obb(center, ax, ay, hx, hy, axis):
    dots = []
    for sx in (-1.0, 1.0):
        for sy in (-1.0, 1.0):
            px = center[0] + ax[0] * (sx * hx) + ay[0] * (sy * hy)
            py = center[1] + ax[1] * (sx * hx) + ay[1] * (sy * hy)
            dots.append(px * axis[0] + py * axis[1])
    return min(dots), max(dots)


def obb_overlap(ma: dict, mb: dict, inflate: float = 0.0) -> bool:
    oa = ma["obb"]
    ob = mb["obb"]

    ca = tuple(oa["center"][:2])
    cb = tuple(ob["center"][:2])
    ax_a, ay_a = oa["ax"], oa["ay"]
    ax_b, ay_b = ob["ax"], ob["ay"]

    hx_a = float(oa["hx"] + inflate)
    hy_a = float(oa["hy"] + inflate)
    hx_b = float(ob["hx"] + inflate)
    hy_b = float(ob["hy"] + inflate)

    axes = [ax_a, ay_a, ax_b, ay_b]
    for axis in axes:
        axis = _normalize2(axis)
        a0, a1 = _project_obb(ca, ax_a, ay_a, hx_a, hy_a, axis)
        b0, b1 = _project_obb(cb, ax_b, ay_b, hx_b, hy_b, axis)
        if a1 < b0 or b1 < a0:
            return False
    return True


def _tri_area2_xy(a: tuple[float, float], b: tuple[float, float], c: tuple[float, float]) -> float:
    return float((b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0]))


def _tri_bbox_xy(tri: tuple[tuple[float, float], tuple[float, float], tuple[float, float]]) -> tuple[float, float, float, float]:
    xs = (tri[0][0], tri[1][0], tri[2][0])
    ys = (tri[0][1], tri[1][1], tri[2][1])
    return (min(xs), max(xs), min(ys), max(ys))


def _point_in_tri_xy(p: tuple[float, float], tri: tuple[tuple[float, float], tuple[float, float], tuple[float, float]], eps: float = 1e-9) -> bool:
    a, b, c = tri
    s1 = _tri_area2_xy(a, b, p)
    s2 = _tri_area2_xy(b, c, p)
    s3 = _tri_area2_xy(c, a, p)
    has_neg = (s1 < -eps) or (s2 < -eps) or (s3 < -eps)
    has_pos = (s1 > eps) or (s2 > eps) or (s3 > eps)
    return not (has_neg and has_pos)


def _on_segment_xy(a: tuple[float, float], b: tuple[float, float], p: tuple[float, float], eps: float = 1e-9) -> bool:
    return (
        min(a[0], b[0]) - eps <= p[0] <= max(a[0], b[0]) + eps
        and min(a[1], b[1]) - eps <= p[1] <= max(a[1], b[1]) + eps
    )


def _segments_intersect_xy(a1, a2, b1, b2, eps: float = 1e-9) -> bool:
    o1 = _tri_area2_xy(a1, a2, b1)
    o2 = _tri_area2_xy(a1, a2, b2)
    o3 = _tri_area2_xy(b1, b2, a1)
    o4 = _tri_area2_xy(b1, b2, a2)

    if ((o1 > eps and o2 < -eps) or (o1 < -eps and o2 > eps)) and ((o3 > eps and o4 < -eps) or (o3 < -eps and o4 > eps)):
        return True

    if abs(o1) <= eps and _on_segment_xy(a1, a2, b1, eps):
        return True
    if abs(o2) <= eps and _on_segment_xy(a1, a2, b2, eps):
        return True
    if abs(o3) <= eps and _on_segment_xy(b1, b2, a1, eps):
        return True
    if abs(o4) <= eps and _on_segment_xy(b1, b2, a2, eps):
        return True

    return False


def _triangles_overlap_xy(
    ta: tuple[tuple[float, float], tuple[float, float], tuple[float, float]],
    tb: tuple[tuple[float, float], tuple[float, float], tuple[float, float]],
    eps: float = 1e-9,
) -> bool:
    a_min_x, a_max_x, a_min_y, a_max_y = _tri_bbox_xy(ta)
    b_min_x, b_max_x, b_min_y, b_max_y = _tri_bbox_xy(tb)
    if a_max_x < b_min_x - eps or b_max_x < a_min_x - eps or a_max_y < b_min_y - eps or b_max_y < a_min_y - eps:
        return False

    ea = ((ta[0], ta[1]), (ta[1], ta[2]), (ta[2], ta[0]))
    eb = ((tb[0], tb[1]), (tb[1], tb[2]), (tb[2], tb[0]))
    for sa0, sa1 in ea:
        for sb0, sb1 in eb:
            if _segments_intersect_xy(sa0, sa1, sb0, sb1, eps=eps):
                return True

    if _point_in_tri_xy(ta[0], tb, eps=eps):
        return True
    if _point_in_tri_xy(tb[0], ta, eps=eps):
        return True
    return False


def _object_world_xy_triangles(obj: bpy.types.Object, min_area: float = 1e-10) -> list[tuple[tuple[float, float], tuple[float, float], tuple[float, float]]]:
    if obj is None or obj.type != "MESH" or obj.data is None:
        return []
    mw = obj.matrix_world
    tris: list[tuple[tuple[float, float], tuple[float, float], tuple[float, float]]] = []
    verts = obj.data.vertices
    for poly in obj.data.polygons:
        idx = list(poly.vertices)
        if len(idx) < 3:
            continue
        p0w = mw @ verts[idx[0]].co
        p0 = (float(p0w.x), float(p0w.y))
        for k in range(1, len(idx) - 1):
            p1w = mw @ verts[idx[k]].co
            p2w = mw @ verts[idx[k + 1]].co
            p1 = (float(p1w.x), float(p1w.y))
            p2 = (float(p2w.x), float(p2w.y))
            if abs(_tri_area2_xy(p0, p1, p2)) > min_area:
                tris.append((p0, p1, p2))
    return tris


def exact_mesh_overlap_xy(obj_a: bpy.types.Object, obj_b: bpy.types.Object) -> bool:
    ta = _object_world_xy_triangles(obj_a)
    tb = _object_world_xy_triangles(obj_b)
    if not ta or not tb:
        return False

    bboxes_a = [_tri_bbox_xy(t) for t in ta]
    bboxes_b = [_tri_bbox_xy(t) for t in tb]

    for i, tri_a in enumerate(ta):
        a_min_x, a_max_x, a_min_y, a_max_y = bboxes_a[i]
        for j, tri_b in enumerate(tb):
            b_min_x, b_max_x, b_min_y, b_max_y = bboxes_b[j]
            if a_max_x < b_min_x or b_max_x < a_min_x or a_max_y < b_min_y or b_max_y < a_min_y:
                continue
            if _triangles_overlap_xy(tri_a, tri_b):
                return True
    return False


def relation_2d_with_pad(target_obj, target_meta, other_obj, other_meta, pad: float) -> str:
    _ = target_meta
    _ = other_meta
    ma = build_collision_meta_from_obj(target_obj)
    mb = build_collision_meta_from_obj(other_obj)
    if ma is None or mb is None:
        return "SAFE"

    pad = float(pad)
    if not aabb_overlap_xy_by_meta(ma, mb, inflate=pad):
        return "SAFE"
    # COLLIDE: use exact projected mesh overlap in XY (avoids OBB false positives on concave footprints).
    if exact_mesh_overlap_xy(target_obj, other_obj):
        return "COLLIDE"
    if obb_overlap(ma, mb, inflate=pad):
        return "NEAR"
    return "SAFE"


def _set_building_rotation_deg(obj, deg: float) -> None:
    obj.rotation_euler[2] = math.radians(deg)
    bpy.context.view_layer.update()


def _reset_building_rotation(obj) -> None:
    obj.rotation_euler[2] = 0.0
    bpy.context.view_layer.update()


def _capture_obj_pose(obj) -> tuple[Vector, tuple[float, float, float]]:
    return obj.location.copy(), tuple(float(v) for v in obj.rotation_euler)


def _restore_obj_pose(obj, pose: tuple[Vector, tuple[float, float, float]]) -> None:
    loc, rot = pose
    obj.location = loc
    obj.rotation_euler = rot
    bpy.context.view_layer.update()


def _object_bbox_center_xy(obj) -> Vector:
    b = _object_world_xy_bounds(obj)
    if b is None:
        return Vector((float(obj.location.x), float(obj.location.y), float(obj.location.z)))
    min_x, max_x, min_y, max_y = b
    return Vector((float((min_x + max_x) * 0.5), float((min_y + max_y) * 0.5), float(obj.location.z)))


def _set_building_rotation_deg_about_bbox_center(obj, deg: float) -> None:
    """
    Rotate object by `deg` (relative) around its current world-space bbox center.
    """
    center = _object_bbox_center_xy(obj)
    loc = obj.location.copy()
    ang = math.radians(float(deg))
    rel_x = float(loc.x - center.x)
    rel_y = float(loc.y - center.y)
    cos_a = math.cos(ang)
    sin_a = math.sin(ang)
    new_x = float(center.x + rel_x * cos_a - rel_y * sin_a)
    new_y = float(center.y + rel_x * sin_a + rel_y * cos_a)
    obj.location = (new_x, new_y, float(loc.z))
    obj.rotation_euler[2] = float(obj.rotation_euler[2]) + ang
    bpy.context.view_layer.update()


def _rotate_dir_to_signed_deg(direction: str, deg: int) -> int:
    return -deg if direction == "cw" else deg


def _dir_token_to_words(direction: str) -> str:
    return "clockwise" if direction == "cw" else "counterclockwise"


def _rotate_building_around_point(obj, point: Vector, angle_deg: float) -> None:
    """Rotate a building around a specified point by the specified angle

    Args:
        obj: Blender building object
        point: rotation center point (Vector)
        angle_deg: rotation angle in degrees
    """
    # Get current object position
    obj_loc = obj.location

    # Compute vector relative to rotation center
    rel_vec = obj_loc - point

    # Rotate around Z axis
    angle_rad = math.radians(angle_deg)
    cos_a = math.cos(angle_rad)
    sin_a = math.sin(angle_rad)

    # New position after rotation
    new_x = point.x + rel_vec.x * cos_a - rel_vec.y * sin_a
    new_y = point.y + rel_vec.x * sin_a + rel_vec.y * cos_a

    obj.location = (new_x, new_y, obj_loc.z)
    obj.rotation_euler[2] = math.radians(angle_deg)
    bpy.context.view_layer.update()


def _reset_building_rotation_and_position(obj, original_loc: Vector) -> None:
    """Reset building position and rotation."""
    obj.location = original_loc
    obj.rotation_euler[2] = 0.0
    bpy.context.view_layer.update()


def _relation_after_rotation(target_obj, target_meta, other_obj, other_meta, signed_deg: float, pad: float) -> str:
    pose = _capture_obj_pose(target_obj)
    try:
        _set_building_rotation_deg_about_bbox_center(target_obj, signed_deg)
        return relation_2d_with_pad(target_obj, target_meta, other_obj, other_meta, pad=pad)
    finally:
        _restore_obj_pose(target_obj, pose)


# ============================================================
# QA tasks
# ============================================================

def _abs_images(sample_dir: str, names: list[str]) -> list[str]:
    return [os.path.abspath(os.path.join(sample_dir, n)) for n in names]


def _camera_forward_world(cam) -> Vector:
    """Get camera forward direction in world space (scene-to-camera direction)."""
    # Get camera rotation matrix
    rot_matrix = cam.matrix_world.to_quaternion().to_matrix()
    # Camera looks along -Z, so Z points opposite the viewing direction
    # Therefore camera forward is the -Z axis
    forward = rot_matrix @ Vector((0, 0, -1))
    return forward.normalized()


def clear_labels_only():
    """Remove all label objects."""
    for obj in list(bpy.data.objects):
        if obj.name.startswith("Label_"):
            bpy.data.objects.remove(obj, do_unlink=True)
    for curve in list(bpy.data.curves):
        if curve.name.startswith("Label_"):
            bpy.data.curves.remove(curve)


def add_label(building_obj, label_text: str, cam, font_size: float = None, building_height: float = None, region_max_dim: float = None) -> None:
    """Add a label to a building

    Args:
        building_obj: Blender building object
        label_text: label text
        cam: camera object
        font_size: font size; auto-computed from building size when None
        building_height: building height, used for label placement
        region_max_dim: region max dimension, used for label placement
    """
    # Get building bounds
    world_matrix = building_obj.matrix_world
    mesh = building_obj.data
    if not mesh:
        return

    if hasattr(building_obj, 'bound_box') and building_obj.bound_box:
        verts = [world_matrix @ Vector(co) for co in building_obj.bound_box]
    else:
        verts = [world_matrix @ v.co for v in mesh.vertices]

    xs = [v.x for v in verts]
    ys = [v.y for v in verts]
    zs = [v.z for v in verts]

    center_x = (min(xs) + max(xs)) / 2
    center_y = (min(ys) + max(ys)) / 2
    center_z = (min(zs) + max(zs)) / 2
    max_z = max(zs)

    # Compute font size
    bounds_width = max(xs) - min(xs)
    bounds_depth = max(ys) - min(ys)
    max_dim = max(bounds_width, bounds_depth)
    if font_size is None:
        font_size = max_dim * 0.4

    text_curve = bpy.data.curves.new(f"Label_{label_text}_curve", type="FONT")
    text_curve.body = str(label_text)
    text_curve.size = font_size
    text_curve.align_x = "CENTER"
    text_curve.align_y = "CENTER"
    text_curve.extrude = max_dim * 0.01
    text_curve.fill_mode = "BOTH"

    text_obj = bpy.data.objects.new(f"Label_{label_text}", text_curve)
    bpy.context.collection.objects.link(text_obj)

    # Label position: above building top (consistent with task2_spatial_orientation)
    if building_height is not None and region_max_dim is not None:
        # Offset by half building height + 3% of region size
        label_z = center_z + building_height / 2 + region_max_dim * 0.03
    else:
        label_z = max_z + font_size * 0.3

    text_obj.location = (center_x, center_y, label_z)

    text_obj.visible_shadow = False
    if hasattr(text_obj, "cycles_visibility"):
        text_obj.cycles_visibility.shadow = False
        text_obj.cycles_visibility.diffuse = False
        text_obj.cycles_visibility.glossy = False
        text_obj.cycles_visibility.ambient_occlusion = False

    billboard = text_obj.constraints.new(type="LOCKED_TRACK")
    billboard.target = cam
    billboard.track_axis = "TRACK_Z"
    billboard.lock_axis = "LOCK_Y"

    lock_roll = text_obj.constraints.new(type="LIMIT_ROTATION")
    lock_roll.owner_space = "LOCAL"
    lock_roll.use_limit_x = False
    lock_roll.use_limit_y = False
    lock_roll.use_limit_z = True
    lock_roll.min_z = 0.0
    lock_roll.max_z = 0.0

    mat = create_black_label_material(f"Label_{label_text}_mat")
    text_obj.data.materials.clear()
    text_obj.data.materials.append(mat)

    bpy.context.view_layer.update()


def render_view(
    cam,
    output_path: str,
    building_objs: list[bpy.types.Object] | None = None,
    isometric: bool = False,
    north_world_dir: Vector = Vector((0.0, 1.0, 0.0)),
    refit_camera: bool = False,
) -> dict | None:
    # Refit can be enabled for rotated option images to keep the target building in frame.
    if refit_camera and building_objs:
        fit_ortho_camera_to_objects(
            cam,
            building_objs,
            margin_ratio=ISO_FIT_MARGIN_RATIO if isometric else TOP_FIT_MARGIN_RATIO,
            min_ortho_scale=MIN_FIT_ORTHO_SCALE,
        )
        bpy.context.view_layer.update()

    scene = bpy.context.scene
    scene.camera = cam
    scene.render.filepath = output_path
    bpy.ops.render.render(write_still=True)

    meta = None
    if building_objs:
        render_rx, render_ry = _render_resolution_px()
        bbox = projected_building_bbox_pixels(cam, building_objs)
        arrow_size = ISO_NORTH_ARROW_SIZE if isometric else TOP_NORTH_ARROW_SIZE
        if TASK3_DYNAMIC_POST_CROP:
            reframe_crop = _compute_reframe_crop_bounds_from_bbox(
                render_rx, render_ry, bbox, REFRAME_PAD_RATIO
            )
            reframe_image_focus_buildings(
                output_path,
                arrow_size=arrow_size,
                reserve_for_north=True,
                building_bbox=bbox,
            )
        else:
            reframe_crop = (0, 0, int(render_rx), int(render_ry))

        north_meta = draw_north_arrow(
            output_path,
            cam=cam,
            north_world_dir=north_world_dir,
            arrow_size=arrow_size,
            corner_idx=0,
            return_meta=True,
        )
        if TASK3_DYNAMIC_POST_CROP:
            trim_meta = trim_image_to_alpha_bbox(output_path, pad_px=FINAL_TRIM_PAD_PX, return_meta=True)
        else:
            nw = int((north_meta or {}).get("final_w", render_rx))
            nh = int((north_meta or {}).get("final_h", render_ry))
            trim_meta = {
                "ok": True,
                "crop_x1": 0,
                "crop_y1": 0,
                "crop_x2": int(nw),
                "crop_y2": int(nh),
                "final_w": int(nw),
                "final_h": int(nh),
            }
        meta = {
            "render_w": int(render_rx),
            "render_h": int(render_ry),
            "building_bbox": bbox,
            "reframe_crop": reframe_crop,
            "north_meta": north_meta,
            "trim_meta": trim_meta,
        }
    return meta


def qa_task1_overlap_yesno(sample_dir: str, target_id: int, other_id: int, direction: str, angle_deg: int) -> dict:
    dir_words = _dir_token_to_words(direction)
    q = (
        "There is one image: a top-view image.\n"
        f"If building {target_id} is rotated {dir_words} by {angle_deg} degrees around its own center, "
        f"will it overlap with building {other_id}? Answer with Yes or No.\n\n"
        "Top-view image: <image>"
    )
    return {
        "question": q,
        "answer": "<to_fill>",
        "task_type": "top_building_rotate_overlap",
        "images": _abs_images(sample_dir, ["top.png"]),
        "meta": {"target_id": target_id, "other_id": other_id, "direction": dir_words, "angle_deg": angle_deg},
    }


def _task2_status_map(target_obj, target_meta, other_obj, other_meta, direction: str) -> dict:
    status = {}
    for deg in ROT_ANGLE_POOL:
        signed = _rotate_dir_to_signed_deg(direction, deg)
        status[deg] = _relation_after_rotation(target_obj, target_meta, other_obj, other_meta, signed_deg=signed, pad=COLLISION_PAD)
    return status


def _ensure_task2_unique_safe_for_direction(target_obj, target_meta, other_obj, other_meta, direction: str):
    status = _task2_status_map(target_obj, target_meta, other_obj, other_meta, direction)
    safe = [d for d, rel in status.items() if rel == "SAFE"]
    collide = [d for d, rel in status.items() if rel == "COLLIDE"]
    if len(safe) < 1 or len(collide) < (ROT_MCQ_K - 1):
        return None
    correct_deg = random.choice(safe)
    options = [correct_deg] + random.sample(collide, ROT_MCQ_K - 1)
    return options, correct_deg


def _pick_task2_direction_and_options(target_obj, target_meta, other_obj, other_meta):
    dirs = ROT_DIR_POOL[:]
    random.shuffle(dirs)
    for d in dirs:
        res = _ensure_task2_unique_safe_for_direction(target_obj, target_meta, other_obj, other_meta, d)
        if res is not None:
            options_deg, correct_deg = res
            return d, options_deg, correct_deg
    return None


def qa_task2_avoid_collision_angle_mcq(sample_dir: str, target_id: int, other_id: int, direction: str, options_deg: list[int], correct_deg: int) -> dict:
    dir_words = _dir_token_to_words(direction)
    labels = ["A", "B", "C", "D"]
    opts = options_deg[:]
    random.shuffle(opts)
    correct_idx = opts.index(correct_deg)
    choices = [f"{labels[i]}. {opts[i]} degrees" for i in range(len(opts))]
    q = (
        "There is one image: a top-view image.\n"
        f"Rotate building {target_id} {dir_words} by one of the angles below (around its own center). "
        f"Which rotation angle avoids overlap with building {other_id}? Choose one option.\n\n"
        "Top-view image: <image>"
    )
    return {
        "question": q + "\n".join(choices),
        "answer": labels[correct_idx],
        "answer_text": f"{correct_deg} degrees",
        "task_type": "top_building_rotate_avoid_overlap",
        "images": _abs_images(sample_dir, ["top.png"]),
        "meta": {"target_id": target_id, "other_id": other_id, "direction": dir_words, "options_deg": opts, "correct_deg": correct_deg},
    }


def qa_task3_rotation_image_mcq(sample_dir: str, target_id: int, direction: str, query_deg: int, option_files: list[str], correct_file: str, view: str = "top") -> dict:
    dir_words = _dir_token_to_words(direction)
    labels = ["A", "B", "C", "D"]
    files = option_files[:]
    random.shuffle(files)
    correct_idx = files.index(correct_file)
    choices = [f"{labels[i]}. <image>" for i in range(len(files))]

    if view == "top":
        q = (
            "There are five images: one original top-view image and four rotated top-view options.\n"
            f"Building {target_id} is rotated {dir_words} by {query_deg} degrees around its center.\n"
            "Which image matches this rotation? Choose one option.\n"
            "Choose one option.\n\n"
            "Original top-view image: <image>\n"
            "A: <image>\n"
            "B: <image>\n"
            "C: <image>\n"
            "D: <image>"
        )
        img_list = [os.path.abspath(os.path.join(sample_dir, "top.png"))] + [os.path.abspath(os.path.join(sample_dir, f)) for f in files]
        task_type = "top_building_rotate"
    else:
        q = (
            "There are five images: one original isometric-view image and four option images.\n"
            f"In the original image, Building {target_id} is rotated {dir_words} by {query_deg} degrees around its center.\n"
            "Which option image shows the correct result after this rotation?\n"
            "Choose one option.\n\n"
            "Original image: <image>\n"
            "A: <image>\n"
            "B: <image>\n"
            "C: <image>\n"
            "D: <image>"
        )

        img_list = [os.path.abspath(os.path.join(sample_dir, "isometric.png"))] + [os.path.abspath(os.path.join(sample_dir, f)) for f in files]
        task_type = "isometric_building_rotate"

    return {
        "question": q,
        "answer": labels[correct_idx],
        "answer_text": os.path.basename(correct_file),
        "task_type": task_type,
        "images": img_list,
        "meta": {"target_id": target_id, "direction": dir_words, "query_deg": query_deg, "files": files, "correct_file": correct_file, "view": view},
    }


def qa_task4_rotation_position_mcq(sample_dir: str, target_id: int, direction: str, query_deg: int, option_files: list[str], correct_file: str, view: str = "top") -> dict:
    """QA4: Given a rotation angle, ask where the building will move after rotating from the original image

    Args:
        sample_dir: sample directory
        target_id: target building ID
        direction: rotation direction (cw/ccw)
        query_deg: rotation angle
        option_files: list of option image files
        correct_file: correct answer image file
        view: view type (top/isometric)
    """
    dir_words = _dir_token_to_words(direction)
    labels = ["A", "B", "C", "D"]
    files = option_files[:]
    random.shuffle(files)
    correct_idx = files.index(correct_file)
    choices = [f"{labels[i]}. <image>" for i in range(len(files))]

    # Get original image path
    if view == "top":
        orig_img = os.path.abspath(os.path.join(sample_dir, "top.png"))
    else:
        orig_img = os.path.abspath(os.path.join(sample_dir, "isometric.png"))

    if view == "top":
        q = (
            "The first image is the original top-view of the region.\n"
            f"In the original image, Building {target_id} is rotated {dir_words} by {query_deg} degrees around the reference center.\n"
            "The reference center is the geometric center of the final top-view image (including the North panel).\n"
            "Which option shows the correct result after this rotation?\n"
            "Answer with A, B, C, or D.\n\n"
            "Original image: <image>\n"
            "A: <image>\n"
            "B: <image>\n"
            "C: <image>\n"
            "D: <image>\n"
            
        )

        img_list = [orig_img] + [os.path.abspath(os.path.join(sample_dir, f)) for f in files]
        task_type = "top_region_building_rotate"

    else:
        q = (
            "The first image is the original isometric view of the region.\n"
            f"In the original image, Building {target_id} is rotated {dir_words} by {query_deg} degrees around the reference center.\n"
            "The reference center is the geometric center of the final top-view image (including the North panel).\n"
            "Which option shows the correct result after this rotation?\n"
            "Answer with A, B, C, or D.\n\n"
            "Original image: <image>\n"
            "A: <image>\n"
            "B: <image>\n"
            "C: <image>\n"
            "D: <image>\n\n"
        )

        img_list = [orig_img] + [os.path.abspath(os.path.join(sample_dir, f)) for f in files]
        task_type = "isometric_region_building_rotate"


    return {
        "question": q + "\n".join(choices),
        "answer": labels[correct_idx],
        "answer_text": os.path.basename(correct_file),
        "task_type": task_type,
        "images": img_list,
        "meta": {"target_id": target_id, "direction": dir_words, "query_deg": query_deg, "files": files, "correct_file": correct_file, "view": view, "rotation_type": "around_region_center"},
    }


# ============================================================
# Main flow
# ============================================================

def calculate_region_bounds(buildings: list) -> dict:
    if not buildings:
        return None
    min_x = min(b["min"][0] for b in buildings)
    max_x = max(b["max"][0] for b in buildings)
    min_y = min(b["min"][1] for b in buildings)
    max_y = max(b["max"][1] for b in buildings)
    min_z = min(b["min"][2] for b in buildings)
    max_z = max(b["max"][2] for b in buildings)
    return {
        "min_x": min_x, "max_x": max_x,
        "min_y": min_y, "max_y": max_y,
        "min_z": min_z, "max_z": max_z,
        "center_x": (min_x + max_x) / 2,
        "center_y": (min_y + max_y) / 2,
        "center_z": (min_z + max_z) / 2,
        "width": max_x - min_x,
        "depth": max_y - min_y,
        "height": max_z - min_z,
    }


def process_region(region_id: int, region_data: dict, all_buildings: list, labeler: BuildingLabeler) -> dict:
    building_ids = region_data["building_ids"]
    region_buildings = get_buildings_in_region(all_buildings, building_ids)

    if len(region_buildings) > MAX_BUILDINGS_PER_REGION:
        print(
            f"  Region {region_id}: Skipped (building count {len(region_buildings)} exceeds limit {MAX_BUILDINGS_PER_REGION})"
        )
        return None

    if len(region_buildings) < 3:
        print(f"  Region {region_id}: Skipped (insufficient buildings: {len(region_buildings)})")
        return None

    print(f"  Region {region_id}: Processing {len(region_buildings)} buildings...")

    bounds = calculate_region_bounds(region_buildings)

    labeler.set_region_visibility(building_ids)
    set_road_visibility(SHOW_ROADS_IN_REGION_RENDER)
    labeler.clear_mask_materials()
    labeler.clear_all_labels()
    apply_white_film_to_buildings(building_ids)
    if SHOW_ROADS_IN_REGION_RENDER:
        apply_road_material()
    labeler.add_building_labels(building_ids, bounds)
    set_all_labels_black()

    cam_top = labeler.setup_camera_top_down(bounds, 'Camera_Top')
    cam_iso = labeler.setup_camera_isometric(bounds, 'Camera_Iso')
    building_objs = get_region_building_objects(building_ids)
    fit_ortho_camera_to_objects(
        cam_top,
        building_objs,
        margin_ratio=TOP_FIT_MARGIN_RATIO,
        min_ortho_scale=MIN_FIT_ORTHO_SCALE,
    )
    fit_ortho_camera_to_objects(
        cam_iso,
        building_objs,
        margin_ratio=ISO_FIT_MARGIN_RATIO,
        min_ortho_scale=MIN_FIT_ORTHO_SCALE,
    )
    # Apply one global margin scale for task3 so all QA images in this region keep a consistent enlarged view.
    margin_scale = max(1.0, float(TASK3_GLOBAL_VIEW_MARGIN_SCALE))
    cam_top.data.ortho_scale = float(cam_top.data.ortho_scale) * margin_scale
    cam_iso.data.ortho_scale = float(cam_iso.data.ortho_scale) * margin_scale
    bpy.context.view_layer.update()

    simple_buildings = []
    for i, b in enumerate(region_buildings):
        simple_buildings.append({
            "label_id": i + 1,
            "original_id": b["id"],
            "center": b["center"],
            "pos": (b["center"][0], b["center"][1]),
            "half_w": b.get("half_w", b["width"] / 2),
            "half_d": b.get("half_d", b["depth"] / 2),
            "height": b["height"],
        })

    # Create output directory structure
    sample_dir = os.path.join(OUTPUT_DIR, f"region_{region_id:03d}")
    os.makedirs(sample_dir, exist_ok=True)
    ref_dir = os.path.join(sample_dir, "ref_rotations")
    os.makedirs(ref_dir, exist_ok=True)
    top_mcq_dir = os.path.join(sample_dir, "top_mcq_images")
    os.makedirs(top_mcq_dir, exist_ok=True)
    iso_mcq_dir = os.path.join(sample_dir, "isometric_mcq_images")
    os.makedirs(iso_mcq_dir, exist_ok=True)
    qa4_top_dir = os.path.join(sample_dir, "top_region_building_rotate_images")
    os.makedirs(qa4_top_dir, exist_ok=True)
    qa4_iso_dir = os.path.join(sample_dir, "iso_region_building_rotate_images")
    os.makedirs(qa4_iso_dir, exist_ok=True)

    # Get building objects from Blender
    building_objs = []
    id_to_obj = {}
    for i, bid in enumerate(building_ids):
        obj = bpy.data.objects.get(bid)
        if obj:
            building_objs.append(obj)
            id_to_obj[i + 1] = obj
            # Ensure object origin is at geometric center (for correct rotation)
            if obj.type == 'MESH' and obj.data:
                # Set origin to geometric center via Blender API
                bpy.ops.object.select_all(action='DESELECT')
                obj.select_set(True)
                bpy.context.view_layer.objects.active = obj
                bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')

    if len(building_objs) < 2:
        print(f"    Warning: insufficient building objects")
        labeler.show_all_visible_objects()
        return None

    # ===== Select target and other building =====
    ids = list(range(1, len(building_objs) + 1))
    target_id = random.choice(ids)
    other_id = random.choice([i for i in ids if i != target_id])
    target_obj = id_to_obj[target_id]
    other_obj = id_to_obj[other_id]
    target_meta = simple_buildings[target_id - 1]
    other_meta = simple_buildings[other_id - 1]

    # ===== Task 1: Will rotation cause overlap? =====
    dir1 = random.choice(ROT_DIR_POOL)
    angle1 = random.choice(ROT_ANGLE_POOL)
    signed1 = _rotate_dir_to_signed_deg(dir1, angle1)
    rel1 = _relation_after_rotation(target_obj, target_meta, other_obj, other_meta, signed1, COLLISION_PAD)
    overlap1 = (rel1 == "COLLIDE")

    qa1 = qa_task1_overlap_yesno(sample_dir, target_id, other_id, dir1, angle1)
    qa1["answer"] = "Yes" if overlap1 else "No"

    # Render QA1 reference images
    clear_labels_only()
    labeler.add_building_labels(building_ids, bounds)
    set_all_labels_black()
    pose_q1 = _capture_obj_pose(target_obj)
    try:
        _set_building_rotation_deg_about_bbox_center(target_obj, signed1)
        force_disable_all_shadows()
        render_view(
            cam_top,
            os.path.join(ref_dir, f"qa1_ref_{dir1}_{angle1:03d}.png"),
            building_objs=building_objs,
            isometric=False,
        )
    finally:
        _restore_obj_pose(target_obj, pose_q1)

    # ===== Task 2: Minimum angle to avoid overlap =====
    task2_result = _pick_task2_direction_and_options(target_obj, target_meta, other_obj, other_meta)
    if task2_result:
        dir2, options_deg, correct_deg = task2_result
        qa2 = qa_task2_avoid_collision_angle_mcq(sample_dir, target_id, other_id, dir2, options_deg, correct_deg)

        # Render QA2 reference images
        for deg in options_deg:
            signed = _rotate_dir_to_signed_deg(dir2, deg)
            clear_labels_only()
            labeler.add_building_labels(building_ids, bounds)
            set_all_labels_black()
            pose_q2 = _capture_obj_pose(target_obj)
            try:
                _set_building_rotation_deg_about_bbox_center(target_obj, signed)
                force_disable_all_shadows()
                render_view(
                    cam_top,
                    os.path.join(ref_dir, f"qa2_ref_{dir2}_{deg:03d}.png"),
                    building_objs=building_objs,
                    isometric=False,
                )
            finally:
                _restore_obj_pose(target_obj, pose_q2)
    else:
        qa2 = None

    # ===== Task 3: Rotation image matching (Top view) =====
    # Generate 4 options (different rotation angles) to ensure distinct visual outcomes
    def _get_unique_self_rotation_options(direction):
        """Get angle options that produce distinct visual outcomes (unique modulo 360)."""
        max_attempts = 100
        for _ in range(max_attempts):
            candidate_degs = random.sample(ROT_ANGLE_POOL, ROT_IMG_MCQ_K)
            # Normalize angles into [0, 360)
            normalized = set(deg % 360 for deg in candidate_degs)
            # Check whether all are unique
            if len(normalized) == ROT_IMG_MCQ_K:
                return candidate_degs
        # If repeated attempts fail, keep candidates and print a warning
        print(f"    Warning: could not find fully distinct rotation angles")
        return candidate_degs

    dir3 = random.choice(ROT_DIR_POOL)
    option_degs = _get_unique_self_rotation_options(dir3)
    query_deg = random.choice(option_degs)

    option_files = []
    correct_file = None

    for deg in option_degs:
        signed = _rotate_dir_to_signed_deg(dir3, deg)
        clear_labels_only()
        pose_q3 = _capture_obj_pose(target_obj)
        try:
            _set_building_rotation_deg_about_bbox_center(target_obj, signed)
            labeler.add_building_labels(building_ids, bounds)
            set_all_labels_black()
            force_disable_all_shadows()
            fn = f"rot_{dir3}_{deg:03d}.png"
            rel_fp = os.path.join("top_mcq_images", fn)
            render_view(
                cam_top,
                os.path.join(sample_dir, rel_fp),
                building_objs=building_objs,
                isometric=False,
            )
        finally:
            _restore_obj_pose(target_obj, pose_q3)
        option_files.append(rel_fp)
        if deg == query_deg:
            correct_file = rel_fp

    if correct_file is None:
        qa3 = None
    else:
        qa3 = qa_task3_rotation_image_mcq(sample_dir, target_id, dir3, query_deg, option_files, correct_file, view="top")

    # ===== Task 3: Rotation image matching (Isometric view) =====
    option_files_iso = []
    correct_file_iso = None

    for deg in option_degs:
        signed = _rotate_dir_to_signed_deg(dir3, deg)
        clear_labels_only()
        pose_q3_iso = _capture_obj_pose(target_obj)
        try:
            _set_building_rotation_deg_about_bbox_center(target_obj, signed)
            labeler.add_building_labels(building_ids, bounds)
            set_all_labels_black()
            force_disable_all_shadows()
            fn = f"iso_rot_{dir3}_{deg:03d}.png"
            rel_fp = os.path.join("isometric_mcq_images", fn)
            render_view(
                cam_iso,
                os.path.join(sample_dir, rel_fp),
                building_objs=building_objs,
                isometric=True,
            )
        finally:
            _restore_obj_pose(target_obj, pose_q3_iso)
        option_files_iso.append(rel_fp)
        if deg == query_deg:
            correct_file_iso = rel_fp

    if correct_file_iso is None:
        qa_iso = None
    else:
        qa_iso = qa_task3_rotation_image_mcq(sample_dir, target_id, dir3, query_deg, option_files_iso, correct_file_iso, view="isometric")

    # ===== Render top.png and isometric.png =====
    print(f"    Rendering top.png...")
    clear_labels_only()
    _reset_building_rotation(target_obj)
    labeler.add_building_labels(building_ids, bounds)
    set_all_labels_black()
    force_disable_all_shadows()
    top_path = os.path.join(sample_dir, "top.png")
    top_render_meta = render_view(
        cam_top,
        top_path,
        building_objs=building_objs,
        isometric=False,
    )

    print(f"    Rendering isometric.png...")
    clear_labels_only()
    _reset_building_rotation(target_obj)
    labeler.add_building_labels(building_ids, bounds)
    set_all_labels_black()
    force_disable_all_shadows()
    iso_path = os.path.join(sample_dir, "isometric.png")
    render_view(
        cam_iso,
        iso_path,
        building_objs=building_objs,
        isometric=True,
    )

    # ===== Task 4: Rotate around region center (Top view) =====
    print(f"    Generating QA4 (rotation around region center)...")
    # Select a different target building for QA4
    all_ids = list(range(1, len(building_objs) + 1))
    qa4_target_id = random.choice([i for i in all_ids if i != target_id])
    qa4_target_obj = id_to_obj[qa4_target_id]
    qa4_target_meta = simple_buildings[qa4_target_id - 1]

    # Region center: back-project the geometric center of final top image (including N panel) to world coordinates
    region_center_ctx = _compute_top_center_world_from_render_meta(cam_top, top_render_meta)
    if region_center_ctx is not None:
        rcx, rcy = region_center_ctx["center_world_xy"]
        region_center = Vector((float(rcx), float(rcy), float(bounds["center_z"])))
    else:
        region_center = Vector((bounds["center_x"], bounds["center_y"], bounds["center_z"]))
    # Save original position
    original_loc = qa4_target_obj.location.copy()

    # Randomly choose rotation direction
    dir4 = random.choice(ROT_DIR_POOL)

    # Generate 4 options (different rotation angles) to ensure distinct positions
    def _get_unique_rotation_options(direction, target_obj, region_center, target_pos):
        """Get rotation-angle options that produce distinct positions."""
        max_attempts = 100
        for _ in range(max_attempts):
            candidate_degs = random.sample(ROT_ANGLE_POOL, ROT_IMG_MCQ_K)
            # Compute position after rotation for each angle
            positions = []
            for deg in candidate_degs:
                signed = _rotate_dir_to_signed_deg(direction, deg)
                # Compute rotated position
                rel_vec = target_pos - region_center
                angle_rad = math.radians(signed)
                cos_a = math.cos(angle_rad)
                sin_a = math.sin(angle_rad)
                new_x = region_center.x + rel_vec.x * cos_a - rel_vec.y * sin_a
                new_y = region_center.y + rel_vec.x * sin_a + rel_vec.y * cos_a
                positions.append((new_x, new_y))
            # Check whether all positions are unique
            if len(set(positions)) == ROT_IMG_MCQ_K:
                return candidate_degs
        # If repeated attempts fail, keep candidates and print a warning
        print(f"    Warning: could not find fully distinct positions; using candidate angles")
        return candidate_degs

    # Get unique position angles
    target_original_pos = Vector((qa4_target_obj.location.x, qa4_target_obj.location.y, 0))
    option_degs4 = _get_unique_rotation_options(dir4, qa4_target_obj, region_center, target_original_pos)
    query_deg4 = random.choice(option_degs4)

    option_files_qa4 = []
    correct_file_qa4 = None

    for deg in option_degs4:
        signed_deg = _rotate_dir_to_signed_deg(dir4, deg)
        clear_labels_only()
        # Rotate building first
        _rotate_building_around_point(qa4_target_obj, region_center, signed_deg)
        # Then add labels via labeler (labels automatically follow building positions)
        labeler.add_building_labels(building_ids, bounds)
        set_all_labels_black()
        force_disable_all_shadows()
        fn = f"rot_center_{dir4}_{deg:03d}.png"
        rel_fp = os.path.join("top_region_building_rotate_images", fn)
        render_view(
            cam_top,
            os.path.join(sample_dir, rel_fp),
            building_objs=building_objs,
            isometric=False,
        )
        # Reset position and rotation
        _reset_building_rotation_and_position(qa4_target_obj, original_loc)
        option_files_qa4.append(rel_fp)
        if deg == query_deg4:
            correct_file_qa4 = rel_fp

    if correct_file_qa4:
        qa4 = qa_task4_rotation_position_mcq(sample_dir, qa4_target_id, dir4, query_deg4, option_files_qa4, correct_file_qa4, view="top")
    else:
        qa4 = None

    # ===== Task 4: Rotate around region center (Isometric view) =====
    option_files_qa4_iso = []
    correct_file_qa4_iso = None

    for deg in option_degs4:
        signed_deg = _rotate_dir_to_signed_deg(dir4, deg)
        clear_labels_only()
        # Rotate building first
        _rotate_building_around_point(qa4_target_obj, region_center, signed_deg)
        # Then add labels via labeler (labels automatically follow building positions)
        labeler.add_building_labels(building_ids, bounds)
        set_all_labels_black()
        force_disable_all_shadows()
        fn = f"iso_rot_center_{dir4}_{deg:03d}.png"
        rel_fp = os.path.join("iso_region_building_rotate_images", fn)
        render_view(
            cam_iso,
            os.path.join(sample_dir, rel_fp),
            building_objs=building_objs,
            isometric=True,
        )
        _reset_building_rotation_and_position(qa4_target_obj, original_loc)
        option_files_qa4_iso.append(rel_fp)
        if deg == query_deg4:
            correct_file_qa4_iso = rel_fp

    if correct_file_qa4_iso:
        qa4_iso = qa_task4_rotation_position_mcq(sample_dir, qa4_target_id, dir4, query_deg4, option_files_qa4_iso, correct_file_qa4_iso, view="isometric")
    else:
        qa4_iso = None

    # Cleanup
    labeler.clear_all_labels()
    labeler.clear_mask_materials()
    labeler.show_all_visible_objects()

    # Assemble QA tasks
    qa_top = [qa1]
    if qa2:
        qa_top.append(qa2)
    if qa3:
        qa_top.append(qa3)
    if qa4:
        qa_top.append(qa4)

    qa_iso = [qa_iso] if qa_iso else []
    if qa4_iso:
        qa_iso.append(qa4_iso)

    return {
        "region_id": region_id,
        "building_count": len(region_buildings),
        "buildings": simple_buildings,
        "images": {
            "top": os.path.abspath(top_path),
            "isometric": os.path.abspath(iso_path),
        },
        "qa": {"top": qa_top, "isometric": qa_iso},
        "special_refs": {
            "target_id": target_id,
            "other_id": other_id,
            "qa4_target_id": qa4_target_id,
            "qa12_self_rotation_center": "building_bbox_center",
            "qa12_collision_mode": "2D_exact_mesh_projection_for_COLLIDE+OBB_pad_for_NEAR",
            "scene_center_definition": "final top-image geometric center (including north panel)",
            "scene_center_world_xy": [float(region_center.x), float(region_center.y)],
        },
    }


def main():
    max_regions = MAX_REGIONS_ARG
    if max_regions is None:
        max_regions = int(os.environ.get("MAX_REGIONS", "0"))
    use_clean = USE_CLEAN_ARG == 1
    if "USE_CLEAN_SCENE" in os.environ:
        use_clean = os.environ.get("USE_CLEAN_SCENE", "1").lower() in ("1", "true", "yes")

    effective_blend_path, effective_region_json_path, failed_region_ids, using_clean = resolve_region_inputs(
        BLEND_PATH,
        REGION_DIR,
        use_clean=use_clean,
    )

    print("=" * 60)
    print(f"Region mental-rotation task generation - Region: {REGION_NAME}")
    print("=" * 60)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print("\n[1/4] Loading data...")
    print(f"  Region: {REGION_NAME}")
    print(f"  BLEND file: {effective_blend_path}")
    print(f"  Region directory: {REGION_DIR}")
    print(f"  Region JSON: {effective_region_json_path}")
    print(f"  Using clean inputs: {using_clean}")
    print(f"  Output directory: {OUTPUT_DIR}")

    all_buildings = load_buildings_from_blend(effective_blend_path)
    print(f"  Loaded buildings: {len(all_buildings)}")

    region_data = load_region_data(effective_region_json_path)
    regions = region_data.get("regions", [])
    raw_region_count = len(regions)
    if failed_region_ids:
        regions = [r for r in regions if int(r.get("region_id", -1)) not in failed_region_ids]
        print(f"  After filtering failed_regions: {len(regions)}/{raw_region_count} regions")
    if max_regions <= 0:
        regions = regions
    else:
        regions = regions[:max_regions]
    print(f"  Region count: {len(regions)}")

    print("\n[2/4] Opening BLEND file...")
    bpy.ops.wm.open_mainfile(filepath=effective_blend_path)
    render_resolution = (RESOLUTION, RESOLUTION) if RESOLUTION > 0 else _render_resolution_px()

    labeler = BuildingLabeler(
        region_data_path=effective_region_json_path,
        blend_path=effective_blend_path,
        output_dir=OUTPUT_DIR,
        ortho_scale_factor=1.3,
        label_height_ratio=0.01,
        font_size_ratio=0.07,
        samples=32,
        resolution=render_resolution,
        mask_alpha=0.8,
    )

    _original_setup_lighting = labeler.setup_lighting

    def _patched_setup_lighting(self):
        scene = bpy.context.scene
        for obj in list(bpy.data.objects):
            if obj.type == 'LIGHT':
                bpy.data.objects.remove(obj)

        sun = bpy.data.objects.new("Sun", bpy.data.lights.new("SunLight", type='SUN'))
        bpy.context.collection.objects.link(sun)
        sun.data.energy = 4.0
        sun.rotation_euler = (math.radians(45), math.radians(15), math.radians(30))
        if hasattr(sun.data, 'cast_shadow'):
            sun.data.cast_shadow = False

        fill_light = bpy.data.objects.new("FillLight", bpy.data.lights.new("FillLight", type='AREA'))
        bpy.context.collection.objects.link(fill_light)
        fill_light.data.energy = 150
        fill_light.location = (0, 0, 100)
        fill_light.data.size = 100
        if hasattr(fill_light.data, 'cast_shadow'):
            fill_light.data.cast_shadow = False

        scene.cycles.use_shadows = False
        scene.cycles.use_progressive = False
        scene.cycles.use_shadow_highlight = False
        scene.cycles.blur_shadow = 0

        for obj in bpy.data.objects:
            if hasattr(obj, 'cycles_visibility'):
                obj.cycles_visibility.cast_shadow = False
                obj.cycles_visibility.receive_shadow = False

    labeler.setup_lighting = types.MethodType(_patched_setup_lighting, labeler)

    labeler.setup_render()
    labeler.setup_lighting()
    force_disable_all_shadows()

    print("\n[3/4] Processing regions...")
    all_results = []
    valid_count = 0

    for region in regions:
        region_id = region["region_id"]
        result = process_region(region_id, region, all_buildings, labeler)
        if result:
            all_results.append(result)
            valid_count += 1

    print(f"\n  Successfully processed {valid_count}/{len(regions)} regions")

    print("\n[4/4] Saving metadata...")
    meta_path = os.path.join(OUTPUT_DIR, "metadata_regions.json")
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2)

    print(f"\nDone!")
    print(f"  Output directory: {OUTPUT_DIR}")
    print(f"  Metadata file: {meta_path}")
    print(f"  Valid regions: {valid_count}")


if __name__ == "__main__":
    main()
