#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import bpy
import os
import sys
import json
import math
import random
import argparse
import subprocess
from itertools import combinations
from mathutils import Vector, Matrix
from bpy_extras.object_utils import world_to_camera_view

# --------------------------------------------------------------------------------------
# Paths / Args
# --------------------------------------------------------------------------------------
PROJECT_ROOT = os.environ.get("PROJECT_ROOT", os.path.expanduser("~/SpatialAct"))
sys.path.insert(0, PROJECT_ROOT)
sys.path.insert(0, os.path.join(PROJECT_ROOT, "src"))
sys.path.insert(0, os.path.join(PROJECT_ROOT, "blender_scripts"))

from src.building_labels import (
    BuildingLabeler,
    is_building as check_is_building,
    is_road,
    apply_road_material,
)

parser = argparse.ArgumentParser(description="Generate region spatial-visualization task data (region version, TOP tasks)")
parser.add_argument("--region", type=str, default=None, help="Region name, e.g., region_a, region_b")
parser.add_argument("--max_regions", type=int, default=0, help="Maximum number of regions to process; 0 = all")
parser.add_argument(
    "--qa-pairs-per-region",
    type=int,
    default=1,
    help="Number of sample groups to generate per region (QA1 move + QA2 swap)",
)
parser.add_argument(
    "--use-clean",
    type=int,
    default=1,
    help="Prefer clean outputs generated by preprocess_clean.py (1=yes, 0=no)",
)
# Blender puts script arguments after "--"; parse only that part to avoid conflicts with Blender args.
argv = sys.argv
if "--" in argv:
    argv = argv[argv.index("--") + 1:]
else:
    argv = []
args, _ = parser.parse_known_args(argv)

REGION_NAME = args.region if args.region else os.environ.get("REGION_NAME", "region")
MAX_REGIONS = int(args.max_regions)
USE_CLEAN_ARG = int(args.use_clean)
QA_PAIRS_PER_REGION = max(1, int(args.qa_pairs_per_region))

BLEND_PATH = os.environ.get(
    "BLEND_PATH",
    os.path.join(PROJECT_ROOT, f"osm_scene_0228/{REGION_NAME}_osm_scene_0228/osm_reference.blend"),
)
REGION_DIR = os.environ.get(
    "REGION_DIR",
    os.path.join(PROJECT_ROOT, f"benchmark/data_construct/model_process/results/{REGION_NAME}_kmeans"),
)
OUTPUT_ROOT = os.environ.get(
    "OUTPUT_ROOT",
    os.path.join(PROJECT_ROOT, "benchmark/data/spatial_visualization"),
)
OUTPUT_DIR = os.path.join(OUTPUT_ROOT, f"{REGION_NAME}_regions")

# --------------------------------------------------------------------------------------
# Config
# --------------------------------------------------------------------------------------
RESOLUTION = int(os.environ.get("RESOLUTION", "0"))  # Use scene resolution when <= 0

MOVE_DIR_POOL = ["E", "W", "N", "S"]
MOVE_DIST_POOL = [1, 2, 3, 5, 6, 10]  # Mix of small and large for diversity
MOVE_TASK_TRIES = 1000
SWAP_TASK_TRIES = 1000

COLLISION_PAD = 0.12  # NEAR band thickness
IN_BOUNDS_MARGIN = 0.5

# Unit conversion: scale movement for visibility in large scenes
UNIT_SCALE = 20.0  # 1 question unit = 20.0 world units in scene

# Scale marker (match reference style)
SCALE_MARK_LENGTH_UNITS = 20.0  # world length used to represent "1 unit" (matches UNIT_SCALE)
SCALE_BAR_THICKNESS = 2  # Main horizontal bar thickness
SCALE_TICK_THICKNESS = 1.0  # Vertical tick terminals - thinner than bar
SCALE_TICK_LEN_Y = 3.5  # Vertical tick length
SCALE_MARK_MARGIN = 1.2
SCALE_MARK_Z_EPS = 0.5  # Keep slightly higher for visibility
SCALE_LABEL_SIZE = 10.0  # Much larger for visibility
SCALE_LABEL_Z_OFF = 2.0
SCALE_PAD_FOR_PLACEMENT = 0.25  # keep scale area free (AABB check)

# Label sizing
LABEL_SIZE_RATIO = 0.07  # of max_dim
LABEL_Z_PAD_RATIO = 0.03
LABEL_COLOR = (0.02, 0.02, 0.02, 1.0)
WHITE_FILM_ALPHA = 0.92
TOP_FIT_MARGIN_RATIO = 0.20
MIN_FIT_ORTHO_SCALE = 2.2
TOP_NORTH_ARROW_SIZE = 96
SHOW_ROADS_IN_REGION_RENDER = os.environ.get("SHOW_ROADS_IN_REGION_RENDER", "1").lower() in ("1", "true", "yes")
MAX_BUILDINGS_PER_REGION = int(os.environ.get("MAX_BUILDINGS_PER_REGION", "15"))
REFRAME_PAD_RATIO = float(os.environ.get("REFRAME_PAD_RATIO", "0.45"))
REFRAME_CONTENT_FILL_RATIO = float(os.environ.get("REFRAME_CONTENT_FILL_RATIO", "1.00"))
FINAL_TRIM_PAD_PX = int(os.environ.get("FINAL_TRIM_PAD_PX", "180"))

# --------------------------------------------------------------------------------------
# Utilities: World bounds / Cleanup
# --------------------------------------------------------------------------------------
def world_bounds_from_obj(obj: bpy.types.Object) -> dict:
    """World-space bounds from obj.bound_box (transformed by matrix_world)."""
    mw = obj.matrix_world
    if hasattr(obj, "bound_box") and obj.bound_box:
        verts = [mw @ Vector(co) for co in obj.bound_box]
    else:
        verts = [mw @ v.co for v in obj.data.vertices]

    xs = [v.x for v in verts]
    ys = [v.y for v in verts]
    zs = [v.z for v in verts]
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    min_z, max_z = min(zs), max(zs)
    return {
        "min_x": float(min_x), "max_x": float(max_x),
        "min_y": float(min_y), "max_y": float(max_y),
        "min_z": float(min_z), "max_z": float(max_z),
        "center_x": float((min_x + max_x) / 2),
        "center_y": float((min_y + max_y) / 2),
        "center_z": float((min_z + max_z) / 2),
        "width": float(max_x - min_x),
        "depth": float(max_y - min_y),
        "height": float(max_z - min_z),
        "half_w": float((max_x - min_x) / 2),
        "half_d": float((max_y - min_y) / 2),
    }


def compute_scene_bounds(objs: list[bpy.types.Object]) -> dict:
    bnds = [world_bounds_from_obj(o) for o in objs if o and o.type == "MESH"]
    min_x = min(b["min_x"] for b in bnds)
    max_x = max(b["max_x"] for b in bnds)
    min_y = min(b["min_y"] for b in bnds)
    max_y = max(b["max_y"] for b in bnds)
    min_z = min(b["min_z"] for b in bnds)
    max_z = max(b["max_z"] for b in bnds)
    return {
        "min_x": float(min_x), "max_x": float(max_x),
        "min_y": float(min_y), "max_y": float(max_y),
        "min_z": float(min_z), "max_z": float(max_z),
        "center_x": float((min_x + max_x) / 2),
        "center_y": float((min_y + max_y) / 2),
        "center_z": float((min_z + max_z) / 2),
        "width": float(max_x - min_x),
        "depth": float(max_y - min_y),
        "height": float(max_z - min_z),
    }


def clear_labels_only() -> None:
    for obj in list(bpy.data.objects):
        if obj.name.startswith("Label_"):
            bpy.data.objects.remove(obj, do_unlink=True)
    for curve in list(bpy.data.curves):
        if curve.name.startswith("Label_"):
            bpy.data.curves.remove(curve)


def clear_overlays_only() -> None:
    for obj in list(bpy.data.objects):
        if obj.name.startswith("Scale_") or obj.name.startswith("Overlay_"):
            bpy.data.objects.remove(obj, do_unlink=True)
    for curve in list(bpy.data.curves):
        if curve.name.startswith("Scale_") or curve.name.startswith("Overlay_"):
            bpy.data.curves.remove(curve)


def _compute_north_screen_vec(cam, north_world_dir: Vector) -> Vector:
    m = cam.matrix_world.to_3x3()
    cam_right = (m @ Vector((1.0, 0.0, 0.0))).normalized()
    cam_up = (m @ Vector((0.0, 1.0, 0.0))).normalized()
    d = north_world_dir.normalized()
    screen_vec = Vector((d.dot(cam_right), -d.dot(cam_up)))
    if screen_vec.length < 1e-6:
        return Vector((0.0, -1.0))
    screen_vec.normalize()
    return screen_vec


def _draw_north_arrow_via_system_python(
    image_path: str,
    screen_vec: Vector,
    arrow_color=(255, 0, 0, 255),
    arrow_size=120,
    corner_idx: int | None = 0,
    unit_bar_px: float | None = None,
    unit_bar_text: str = "1 unit",
) -> bool:
    payload = {
        "image_path": image_path,
        "screen_vec": [float(screen_vec.x), float(screen_vec.y)],
        "arrow_color": [int(arrow_color[0]), int(arrow_color[1]), int(arrow_color[2]), int(arrow_color[3])],
        "arrow_size": int(arrow_size),
        "corner_idx": (int(corner_idx) if corner_idx is not None else None),
        "unit_bar_px": (float(unit_bar_px) if unit_bar_px is not None else None),
        "unit_bar_text": str(unit_bar_text),
        "unit_bar_color": [255, 255, 255, 255],
    }
    helper_script = r"""
import json, os, sys
from PIL import Image, ImageDraw, ImageFont

def load_font(sz):
    for fp in [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf",
    ]:
        if os.path.exists(fp):
            try:
                return ImageFont.truetype(fp, sz)
            except Exception:
                pass
    return ImageFont.load_default()

def norm2(x, y):
    n = (x * x + y * y) ** 0.5
    if n < 1e-8:
        return 0.0, -1.0
    return x / n, y / n

payload = json.loads(sys.argv[1])
image_path = payload["image_path"]
if not os.path.exists(image_path):
    raise SystemExit(0)
vx, vy = norm2(float(payload["screen_vec"][0]), float(payload["screen_vec"][1]))
arrow_color = tuple(payload["arrow_color"])
arrow_size = int(payload["arrow_size"])
unit_bar_color = tuple(int(v) for v in payload.get("unit_bar_color", [255, 255, 255, 255]))

img = Image.open(image_path).convert("RGBA")
draw = ImageDraw.Draw(img)
w, h = img.size
alpha = img.getchannel("A")
pix = img.load()
margin = max(16, int(arrow_size * 0.20))
unit_bar_px = payload.get("unit_bar_px", None)
unit_bar_text = str(payload.get("unit_bar_text", "1 unit"))
bar_need_px = 0
if unit_bar_px is not None:
    try:
        u = float(unit_bar_px)
        if u < 0.0:
            u = 0.0
        bar_need_px = int(u + 0.999) + int(arrow_size * 0.56)
    except Exception:
        bar_need_px = 0
panel_w = max(int(arrow_size * 1.75), bar_need_px)
panel_h = int(arrow_size * 2.25)
cands = [
    (w - margin - panel_w, margin),
    (margin, margin),
    (w - margin - panel_w, h - margin - panel_h),
    (margin, h - margin - panel_h),
]
corner_idx = payload.get("corner_idx", 0)

def overlap_ratio(px, py):
    x1 = max(0, int(px)); y1 = max(0, int(py))
    x2 = min(w, x1 + panel_w); y2 = min(h, y1 + panel_h)
    if x2 <= x1 or y2 <= y1:
        return 1.0
    patch = alpha.crop((x1, y1, x2, y2))
    hist = patch.histogram()
    non_transparent = (x2 - x1) * (y2 - y1) - hist[0]
    return non_transparent / float((x2 - x1) * (y2 - y1))

def is_building_pixel(r, g, b, a):
    if a <= 0:
        return False
    # Ignore common road-yellow pixels to avoid treating roads as buildings
    is_yellow_road = (r > 150 and g > 150 and b < 120 and abs(r - g) < 80)
    return (not is_yellow_road)

def panel_overlaps_buildings(px, py):
    x1 = max(0, int(px))
    y1 = max(0, int(py))
    x2 = min(w, x1 + panel_w)
    y2 = min(h, y1 + panel_h)
    if x2 <= x1 or y2 <= y1:
        return False
    for yy in range(y1, y2):
        for xx in range(x1, x2):
            r, g, b, a = pix[xx, yy]
            if is_building_pixel(r, g, b, a):
                return True
    return False

if isinstance(corner_idx, int) and 0 <= corner_idx < len(cands):
    bx, by = cands[corner_idx]
else:
    bx, by = min(cands, key=lambda xy: overlap_ratio(xy[0], xy[1]))

x1, y1 = int(bx), int(by)
x2, y2 = x1 + panel_w, y1 + panel_h

# If it overlaps building pixels, extend the right side (and top if needed) and place N in the extension so buildings are never covered.
if panel_overlaps_buildings(x1, y1):
    old_w, old_h = w, h
    ext_w = panel_w + 2 * margin
    ext_top = max(0, panel_h + 2 * margin - old_h)
    new_w = old_w + ext_w
    new_h = old_h + ext_top

    new_img = Image.new("RGBA", (new_w, new_h), (0, 0, 0, 0))
    new_img.paste(img, (0, ext_top), img)
    img = new_img
    draw = ImageDraw.Draw(img)
    pix = img.load()
    w, h = img.size

    x1 = old_w + max(0, (ext_w - panel_w) // 2)
    y1 = margin

x2, y2 = x1 + panel_w, y1 + panel_h
draw.rectangle([x1, y1, x2, y2], fill=(0, 0, 0, 220))
layout_shift = -0.10 * panel_h
cx = x1 + panel_w * 0.63
cy = y1 + panel_h * 0.34 + layout_shift
arrow_len = arrow_size * 0.52
head = arrow_size * 0.20
shaft_w = max(3, int(arrow_size * 0.05))
px, py = -vy, vx

tip = (cx + vx * arrow_len * 0.5, cy + vy * arrow_len * 0.5)
bottom = (cx - vx * arrow_len * 0.5, cy - vy * arrow_len * 0.5)
wing_base = (tip[0] - vx * head, tip[1] - vy * head)
left_wing = (wing_base[0] + px * head * 0.58, wing_base[1] + py * head * 0.58)
right_wing = (wing_base[0] - px * head * 0.58, wing_base[1] - py * head * 0.58)
draw.line([bottom, tip], fill=arrow_color, width=shaft_w)
draw.polygon([tip, left_wing, right_wing], fill=arrow_color)
font = load_font(max(16, int(arrow_size * 0.34)))
if font is not None:
    draw.text((x1 + panel_w * 0.20, y1 + panel_h * 0.50 + layout_shift), "N", fill=arrow_color, font=font)

if unit_bar_px is not None:
    try:
        bar_len = max(1.0, float(unit_bar_px))
        bar_y = y1 + panel_h * 0.84 + layout_shift
        bar_cx = x1 + panel_w * 0.50
        bar_left = bar_cx - bar_len * 0.5
        bar_right = bar_cx + bar_len * 0.5

        max_right = x1 + panel_w * 0.94
        if bar_right > max_right:
            shift = bar_right - max_right
            bar_left -= shift
            bar_right -= shift

        min_left = x1 + panel_w * 0.06
        if bar_left < min_left:
            bar_left = min_left
            bar_right = bar_left + bar_len

        bar_w = max(3, int(arrow_size * 0.045))
        tick_h = max(4, int(arrow_size * 0.085))
        draw.line([(bar_left, bar_y), (bar_right, bar_y)], fill=unit_bar_color, width=bar_w)
        draw.line([(bar_left, bar_y - tick_h), (bar_left, bar_y + tick_h)], fill=unit_bar_color, width=bar_w)
        draw.line([(bar_right, bar_y - tick_h), (bar_right, bar_y + tick_h)], fill=unit_bar_color, width=bar_w)

        lbl_font = load_font(max(16, int(arrow_size * 0.24)))
        if lbl_font is not None:
            bbox = draw.textbbox((0, 0), unit_bar_text, font=lbl_font)
            tw = bbox[2] - bbox[0]
            tx2 = (bar_left + bar_right - tw) * 0.5
            ty2 = bar_y + tick_h + max(3, int(arrow_size * 0.035))
            if ty2 + (bbox[3] - bbox[1]) > y1 + panel_h:
                ty2 = y1 + panel_h - (bbox[3] - bbox[1]) - 2
            if ty2 < y1 + 2:
                ty2 = y1 + 2
            draw.text((tx2, ty2), unit_bar_text, fill=unit_bar_color, font=lbl_font)
    except Exception:
        pass
img.save(image_path)
"""
    try:
        subprocess.run(
            ["python3", "-c", helper_script, json.dumps(payload, ensure_ascii=False)],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        return True
    except Exception as e:
        print(f"[WARN] draw north failed for {image_path}: {e}")
        return False


def draw_north_arrow(
    image_path: str,
    cam,
    north_world_dir=Vector((0.0, 1.0, 0.0)),
    arrow_size: int = TOP_NORTH_ARROW_SIZE,
    corner_idx: int | None = None,
    add_unit_bar: bool = False,
) -> str:
    if not os.path.exists(image_path):
        return image_path
    sv = _compute_north_screen_vec(cam, north_world_dir)
    unit_bar_px = _unit_bar_length_px(cam, unit_world=SCALE_MARK_LENGTH_UNITS) if add_unit_bar else None
    _draw_north_arrow_via_system_python(
        image_path,
        sv,
        arrow_color=(255, 0, 0, 255),
        arrow_size=arrow_size,
        corner_idx=corner_idx,
        unit_bar_px=unit_bar_px,
        unit_bar_text="1 unit",
    )
    return image_path


def reframe_image_focus_buildings(
    image_path: str,
    pad_ratio: float | None = None,
    content_fill_ratio: float | None = None,
    arrow_size: int | None = None,
    reserve_for_north: bool = True,
    building_bbox: tuple[int, int, int, int] | None = None,
) -> bool:
    if not os.path.exists(image_path):
        return False
    if pad_ratio is None:
        pad_ratio = REFRAME_PAD_RATIO
    if content_fill_ratio is None:
        content_fill_ratio = REFRAME_CONTENT_FILL_RATIO
    payload = {
        "image_path": image_path,
        "pad_ratio": float(max(0.0, min(0.5, pad_ratio))),
        "content_fill_ratio": float(max(0.35, min(1.0, content_fill_ratio))),
        "arrow_size": (int(arrow_size) if arrow_size is not None else None),
        "reserve_for_north": bool(reserve_for_north),
        "building_bbox": (
            [int(building_bbox[0]), int(building_bbox[1]), int(building_bbox[2]), int(building_bbox[3])]
            if building_bbox is not None else None
        ),
    }
    helper_script = r"""
import json, os, sys
from PIL import Image

payload = json.loads(sys.argv[1])
image_path = payload["image_path"]
if not os.path.exists(image_path):
    raise SystemExit(0)

pad_ratio = float(payload.get("pad_ratio", 0.10))
bbox = payload.get("building_bbox", None)

img = Image.open(image_path).convert("RGBA")
w, h = img.size
pix = img.load()

if isinstance(bbox, list) and len(bbox) == 4:
    x1 = max(0, min(w - 1, int(bbox[0])))
    y1 = max(0, min(h - 1, int(bbox[1])))
    x2 = max(0, min(w - 1, int(bbox[2])))
    y2 = max(0, min(h - 1, int(bbox[3])))
    if x2 < x1:
        x1, x2 = x2, x1
    if y2 < y1:
        y1, y2 = y2, y1
else:
    xs = []
    ys = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = pix[x, y]
            if a <= 0:
                continue
            # White-film buildings: relatively bright and not yellowish
            if (r > 140 and g > 140 and b > 140) and (abs(r - g) < 45 and abs(r - b) < 45 and abs(g - b) < 45):
                xs.append(x)
                ys.append(y)
    if not xs or not ys:
        # Fallback: use all non-transparent pixels
        for y in range(h):
            for x in range(w):
                if pix[x, y][3] > 0:
                    xs.append(x)
                    ys.append(y)
    if not xs or not ys:
        raise SystemExit(0)
    x1, x2 = min(xs), max(xs)
    y1, y2 = min(ys), max(ys)
bw = max(1, x2 - x1 + 1)
bh = max(1, y2 - y1 + 1)
pad_x = int(round(bw * pad_ratio))
pad_y = int(round(bh * pad_ratio))

x1 = max(0, x1 - pad_x)
y1 = max(0, y1 - pad_y)
x2 = min(w - 1, x2 + pad_x)
y2 = min(h - 1, y2 + pad_y)

crop = img.crop((x1, y1, x2 + 1, y2 + 1))
cw, ch = crop.size
if cw <= 0 or ch <= 0:
    raise SystemExit(0)
crop.save(image_path)
"""
    try:
        subprocess.run(
            ["python3", "-c", helper_script, json.dumps(payload, ensure_ascii=False)],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        return True
    except Exception as e:
        print(f"  [reframe] Warning: reframing failed for {image_path}: {e}")
        return False


def trim_image_to_alpha_bbox(image_path: str, pad_px: int = 0) -> bool:
    if not os.path.exists(image_path):
        return False
    payload = {
        "image_path": image_path,
        "pad_px": int(max(0, pad_px)),
    }
    helper_script = r"""
import json, os, sys
from PIL import Image

payload = json.loads(sys.argv[1])
image_path = payload["image_path"]
pad = int(payload.get("pad_px", 0))
if not os.path.exists(image_path):
    raise SystemExit(0)

img = Image.open(image_path).convert("RGBA")
w, h = img.size
x1 = y1 = x2 = y2 = None
pix = img.load()
for y in range(h):
    for x in range(w):
        r, g, b, a = pix[x, y]
        if a <= 0:
            continue
        # Ignore common yellow road pixels to prevent roads from over-expanding the crop box
        is_yellow_road = (r > 150 and g > 150 and b < 120 and abs(r - g) < 80)
        if is_yellow_road:
            continue
        if x1 is None:
            x1 = x2 = x
            y1 = y2 = y
        else:
            if x < x1: x1 = x
            if y < y1: y1 = y
            if x > x2: x2 = x
            if y > y2: y2 = y

if x1 is None:
    alpha = img.getchannel("A")
    bbox = alpha.getbbox()
    if bbox is None:
        raise SystemExit(0)
    x1, y1, x2, y2 = bbox
else:
    x2 += 1
    y2 += 1

x1 = max(0, x1 - pad)
y1 = max(0, y1 - pad)
x2 = min(w, x2 + pad)
y2 = min(h, y2 + pad)
if x2 <= x1 or y2 <= y1:
    raise SystemExit(0)
img.crop((x1, y1, x2, y2)).save(image_path)
"""
    try:
        subprocess.run(
            ["python3", "-c", helper_script, json.dumps(payload, ensure_ascii=False)],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        return True
    except Exception as e:
        print(f"  [trim] Warning: trim failed for {image_path}: {e}")
        return False


def _iter_object_world_vertices(obj):
    if obj is None or obj.type != "MESH":
        return
    mesh = obj.data
    if not mesh.vertices:
        return
    used = set()
    for poly in mesh.polygons:
        for vid in poly.vertices:
            used.add(int(vid))
    if used:
        for vid in used:
            yield obj.matrix_world @ mesh.vertices[vid].co
    else:
        for v in mesh.vertices:
            yield obj.matrix_world @ v.co


def _render_resolution_px() -> tuple[int, int]:
    scene = bpy.context.scene
    rx = int(scene.render.resolution_x * scene.render.resolution_percentage / 100.0)
    ry = int(scene.render.resolution_y * scene.render.resolution_percentage / 100.0)
    return max(1, rx), max(1, ry)


def _camera_half_extents(cam: bpy.types.Object) -> tuple[float, float]:
    frame = cam.data.view_frame(scene=bpy.context.scene)
    hx = max(abs(v.x) for v in frame)
    hy = max(abs(v.y) for v in frame)
    return float(hx), float(hy)


def _unit_bar_length_px(cam: bpy.types.Object, unit_world: float = 1.0) -> float:
    if cam is None or cam.type != "CAMERA" or cam.data.type != "ORTHO":
        return 0.0
    hx, _ = _camera_half_extents(cam)
    rx, _ = _render_resolution_px()
    if hx <= 1e-8:
        return 0.0
    px_per_world_x = float(rx) / (2.0 * hx)
    return float(unit_world) * px_per_world_x


def fit_ortho_camera_to_objects(cam, objects: list, margin_ratio: float = 0.08, min_ortho_scale: float = 2.2) -> None:
    if cam is None or cam.type != "CAMERA" or cam.data.type != "ORTHO":
        return
    world_points = []
    for obj in objects:
        for p in _iter_object_world_vertices(obj):
            world_points.append(p)
    if not world_points:
        return
    wx = [float(p.x) for p in world_points]
    wy = [float(p.y) for p in world_points]
    cam.location.x = 0.5 * (min(wx) + max(wx))
    cam.location.y = 0.5 * (min(wy) + max(wy))
    bpy.context.view_layer.update()
    fit_half_x = 0.5 * (max(wx) - min(wx))
    fit_half_y = 0.5 * (max(wy) - min(wy))
    rx, ry = _render_resolution_px()
    aspect = float(rx) / float(max(1, ry))
    needed_scale = max(2.0 * fit_half_x, 2.0 * fit_half_y * aspect)
    cam.data.ortho_scale = max(min_ortho_scale, needed_scale * (1.0 + margin_ratio))


def create_white_film_material(name: str = "Mask_WhiteFilm") -> bpy.types.Material:
    if name in bpy.data.materials:
        return bpy.data.materials[name]
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    mat.blend_method = "BLEND" if WHITE_FILM_ALPHA < 0.995 else "OPAQUE"
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()
    out = nodes.new("ShaderNodeOutputMaterial")
    em = nodes.new("ShaderNodeEmission")
    em.inputs["Color"].default_value = (1.0, 1.0, 1.0, 1.0)
    em.inputs["Strength"].default_value = 1.0
    if WHITE_FILM_ALPHA < 0.995:
        tr = nodes.new("ShaderNodeBsdfTransparent")
        mix = nodes.new("ShaderNodeMixShader")
        mix.inputs["Fac"].default_value = WHITE_FILM_ALPHA
        links.new(tr.outputs["BSDF"], mix.inputs[1])
        links.new(em.outputs["Emission"], mix.inputs[2])
        links.new(mix.outputs["Shader"], out.inputs["Surface"])
    else:
        links.new(em.outputs["Emission"], out.inputs["Surface"])
    return mat


def apply_white_film_to_buildings(building_ids: list[str]) -> None:
    mat = create_white_film_material()
    for bid in building_ids:
        obj = bpy.data.objects.get(bid)
        if not obj or obj.type != "MESH":
            continue
        obj.data.materials.clear()
        obj.data.materials.append(mat)
        obj.visible_shadow = False
        if hasattr(obj, "cycles_visibility"):
            obj.cycles_visibility.shadow = False


def set_road_visibility(visible: bool) -> None:
    for obj in bpy.data.objects:
        if obj.type != "MESH":
            continue
        if not is_road(obj.name):
            continue
        obj.hide_set(not visible)
        obj.hide_render = (not visible)


def create_black_label_material(name: str = "Label_Black_Mat") -> bpy.types.Material:
    if name in bpy.data.materials:
        return bpy.data.materials[name]
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()
    out = nodes.new("ShaderNodeOutputMaterial")
    bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    bsdf.inputs["Base Color"].default_value = LABEL_COLOR
    bsdf.inputs["Roughness"].default_value = 0.25
    bsdf.inputs["Specular"].default_value = 0.28
    links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])
    return mat


# --------------------------------------------------------------------------------------
# Render settings / Shadows off
# --------------------------------------------------------------------------------------
def setup_render(resolution: int | tuple[int, int] = 1080) -> None:
    scene = bpy.context.scene
    scene.render.engine = "CYCLES"
    scene.cycles.device = "CPU"
    scene.cycles.samples = 32
    if isinstance(resolution, tuple):
        rx, ry = int(resolution[0]), int(resolution[1])
    else:
        rx = int(resolution)
        ry = int(resolution)
    scene.render.resolution_x = max(1, rx)
    scene.render.resolution_y = max(1, ry)
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    scene.render.film_transparent = True


def force_disable_all_shadows_and_world() -> None:
    scene = bpy.context.scene
    scene.cycles.use_shadows = False
    scene.cycles.use_progressive = False
    scene.cycles.use_shadow_highlight = False
    scene.cycles.blur_shadow = 0

    for obj in bpy.data.objects:
        if obj.type == "LIGHT":
            if hasattr(obj.data, "use_shadow"):
                obj.data.use_shadow = False
            if hasattr(obj.data, "cast_shadow"):
                obj.data.cast_shadow = False

    for obj in bpy.data.objects:
        if hasattr(obj, "cycles_visibility"):
            obj.cycles_visibility.cast_shadow = False
            obj.cycles_visibility.receive_shadow = False

    # Transparent background: keep world strength at 0 only
    if bpy.context.scene.world is None:
        bpy.context.scene.world = bpy.data.worlds.new("World")
    world = bpy.context.scene.world
    world.use_nodes = True
    nodes = world.node_tree.nodes
    links = world.node_tree.links
    nodes.clear()
    links.clear()
    out = nodes.new("ShaderNodeOutputWorld")
    bg = nodes.new("ShaderNodeBackground")
    bg.inputs["Color"].default_value = (1.0, 1.0, 1.0, 1.0)
    bg.inputs["Strength"].default_value = 0.0
    links.new(bg.outputs["Background"], out.inputs["Surface"])


# --------------------------------------------------------------------------------------
# Move-effect auto-detect + bake (critical for move/swap after rendering correctness)
# --------------------------------------------------------------------------------------
def does_location_move_geometry(obj: bpy.types.Object, delta_x: float = UNIT_SCALE) -> bool:
    """Test if changing obj.location changes its world bounds center."""
    b0 = world_bounds_from_obj(obj)
    old_loc = obj.location.copy()
    obj.location.x += float(delta_x)
    bpy.context.view_layer.update()
    b1 = world_bounds_from_obj(obj)
    obj.location = old_loc
    bpy.context.view_layer.update()
    dx = abs(b1["center_x"] - b0["center_x"])
    return dx > (abs(delta_x) * 0.6)


def bake_mesh_to_local_and_reset_transform(obj: bpy.types.Object) -> None:
    """
    Bake current world transform into mesh vertex positions, then reset matrix_world to identity.
    After this, obj.location will reliably move the geometry.
    """
    if obj.type != "MESH" or obj.data is None:
        return

    mw = obj.matrix_world.copy()

    # Write world coords into local vertex coords
    mesh = obj.data
    for v in mesh.vertices:
        v.co = mw @ v.co
    mesh.update()

    # Reset transform
    obj.matrix_world = Matrix.Identity(4)
    bpy.context.view_layer.update()


def ensure_buildings_movable(building_objs: list[bpy.types.Object]) -> None:
    """
    If location does not move geometry, bake all buildings once.
    """
    if not building_objs:
        return
    test = building_objs[0]
    if does_location_move_geometry(test):
        print("[INFO] location affects geometry -> no bake needed")
        return

    print("[WARN] location does NOT affect geometry -> baking buildings to local space...")
    for o in building_objs:
        bake_mesh_to_local_and_reset_transform(o)

    bpy.context.view_layer.update()
    # Re-test
    if not does_location_move_geometry(building_objs[0]):
        print("[ERROR] bake did not make buildings movable; move/swap after render may still be wrong.")


# --------------------------------------------------------------------------------------
# PCA OBB footprint computation (2D)
# --------------------------------------------------------------------------------------
def compute_pca_obb_xy(world_xy_pts: list[tuple[float, float]]) -> dict | None:
    """
    Given 2D points in world XY, compute an oriented bounding box using PCA.
    Return:
      angle (radians), ax, ay, hx, hy, center (cx,cy)
    """
    if not world_xy_pts:
        return None
    n = len(world_xy_pts)
    mx = sum(p[0] for p in world_xy_pts) / n
    my = sum(p[1] for p in world_xy_pts) / n
    xx = sum((p[0] - mx) ** 2 for p in world_xy_pts)
    yy = sum((p[1] - my) ** 2 for p in world_xy_pts)
    xy = sum((p[0] - mx) * (p[1] - my) for p in world_xy_pts)

    if abs(xy) < 1e-9:
        angle = 0.0 if xx >= yy else (math.pi / 2.0)
    else:
        angle = 0.5 * math.atan2(2.0 * xy, xx - yy)

    ca = math.cos(angle)
    sa = math.sin(angle)
    ax = (ca, sa)
    ay = (-sa, ca)

    # Rotate points into OBB frame
    rot = []
    for (x, y) in world_xy_pts:
        dx = x - mx
        dy = y - my
        rx = ca * dx + sa * dy
        ry = -sa * dx + ca * dy
        rot.append((rx, ry))

    rxs = [p[0] for p in rot]
    rys = [p[1] for p in rot]
    min_rx, max_rx = min(rxs), max(rxs)
    min_ry, max_ry = min(rys), max(rys)

    hx = 0.5 * (max_rx - min_rx)
    hy = 0.5 * (max_ry - min_ry)
    # OBB center in rotated frame
    crx = 0.5 * (min_rx + max_rx)
    cry = 0.5 * (min_ry + max_ry)
    # Convert center back to world
    cx = mx + ca * crx - sa * cry
    cy = my + sa * crx + ca * cry

    return {
        "angle": float(angle),
        "ax": (float(ax[0]), float(ax[1])),
        "ay": (float(ay[0]), float(ay[1])),
        "hx": float(hx),
        "hy": float(hy),
        "center": (float(cx), float(cy)),
    }


def build_meta_from_obj(obj: bpy.types.Object, label_id: int) -> dict:
    """
    Build collision/render meta from the current object:
    - pos: obj.location xy (consistent with rendering-time movement)
    - half_w/half_d: world AABB half extents
    - obb: PCA OBB on footprint sampled from vertices projected to XY
    """
    b = world_bounds_from_obj(obj)

    # Key point: use obj.location as pos so it stays consistent with obj.location movement during rendering
    pos_x = float(obj.location.x)
    pos_y = float(obj.location.y)

    # Sample footprint points: project vertices to XY.
    # To keep it fast, sample up to N vertices.
    mw = obj.matrix_world
    verts = obj.data.vertices
    pts = []
    step = max(1, len(verts) // 500)  # cap ~500 samples
    for i in range(0, len(verts), step):
        w = mw @ verts[i].co
        pts.append((float(w.x), float(w.y)))

    obb = compute_pca_obb_xy(pts)  # None if no pts
    if obb is None:
        obb = {
            "angle": 0.0,
            "ax": (1.0, 0.0),
            "ay": (0.0, 1.0),
            "hx": b["half_w"],
            "hy": b["half_d"],
            "center": (pos_x, pos_y),
        }

    return {
        "label_id": int(label_id),
        "original_id": obj.name,
        "pos": (pos_x, pos_y),
        "half_w": float(b["half_w"]),
        "half_d": float(b["half_d"]),
        "height": float(b["height"]),
        "obb": obb,  # world-frame OBB
    }


# --------------------------------------------------------------------------------------
# Collision: AABB precheck + OBB overlap (SAT)
# --------------------------------------------------------------------------------------
def aabb_overlap_xy_by_meta(ma: dict, mb: dict, inflate: float = 0.0, pos_a=None, pos_b=None) -> bool:
    # Use obb center if no pos override provided
    ax, ay = pos_a if pos_a is not None else tuple(ma["obb"]["center"][:2])
    bx, by = pos_b if pos_b is not None else tuple(mb["obb"]["center"][:2])
    inf = float(inflate)
    # Use half_w/half_d (axis-aligned AABB) for quick precheck
    # This is more accurate than using rotated OBB hx/hy
    min_ax = ax - ma["half_w"] - inf
    max_ax = ax + ma["half_w"] + inf
    min_ay = ay - ma["half_d"] - inf
    max_ay = ay + ma["half_d"] + inf

    min_bx = bx - mb["half_w"] - inf
    max_bx = bx + mb["half_w"] + inf
    min_by = by - mb["half_d"] - inf
    max_by = by + mb["half_d"] + inf

    if max_ax < min_bx or min_ax > max_bx:
        return False
    if max_ay < min_by or min_ay > max_by:
        return False
    return True


def _normalize2(v: tuple[float, float]) -> tuple[float, float]:
    l = math.hypot(v[0], v[1])
    if l < 1e-9:
        return (1.0, 0.0)
    return (v[0] / l, v[1] / l)


def _project_obb(center, ax, ay, hx, hy, axis):
    dots = []
    for sx in (-1.0, 1.0):
        for sy in (-1.0, 1.0):
            px = center[0] + ax[0] * (sx * hx) + ay[0] * (sy * hy)
            py = center[1] + ax[1] * (sx * hx) + ay[1] * (sy * hy)
            dots.append(px * axis[0] + py * axis[1])
    return min(dots), max(dots)


def obb_overlap(ma: dict, mb: dict, inflate: float = 0.0, pos_a=None, pos_b=None) -> bool:
    oa = ma["obb"]
    ob = mb["obb"]

    # Use obb center if no pos override, otherwise use pos directly as new center
    ca = tuple(pos_a[:2]) if pos_a is not None else tuple(oa["center"][:2])
    cb = tuple(pos_b[:2]) if pos_b is not None else tuple(ob["center"][:2])

    ax_a, ay_a = oa["ax"], oa["ay"]
    ax_b, ay_b = ob["ax"], ob["ay"]

    hx_a = float(oa["hx"] + inflate)
    hy_a = float(oa["hy"] + inflate)
    hx_b = float(ob["hx"] + inflate)
    hy_b = float(ob["hy"] + inflate)

    axes = [ax_a, ay_a, ax_b, ay_b]
    for axis in axes:
        axis = _normalize2(axis)
        a0, a1 = _project_obb(ca, ax_a, ay_a, hx_a, hy_a, axis)
        b0, b1 = _project_obb(cb, ax_b, ay_b, hx_b, hy_b, axis)
        if a1 < b0 or b1 < a0:
            return False
    return True


def _tri_area2_xy(a: tuple[float, float], b: tuple[float, float], c: tuple[float, float]) -> float:
    return float((b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0]))


def _tri_bbox_xy(tri: tuple[tuple[float, float], tuple[float, float], tuple[float, float]]) -> tuple[float, float, float, float]:
    xs = (tri[0][0], tri[1][0], tri[2][0])
    ys = (tri[0][1], tri[1][1], tri[2][1])
    return (min(xs), max(xs), min(ys), max(ys))


def _point_in_tri_xy(
    p: tuple[float, float],
    tri: tuple[tuple[float, float], tuple[float, float], tuple[float, float]],
    eps: float = 1e-9,
) -> bool:
    a, b, c = tri
    s1 = _tri_area2_xy(a, b, p)
    s2 = _tri_area2_xy(b, c, p)
    s3 = _tri_area2_xy(c, a, p)
    has_neg = (s1 < -eps) or (s2 < -eps) or (s3 < -eps)
    has_pos = (s1 > eps) or (s2 > eps) or (s3 > eps)
    return not (has_neg and has_pos)


def _on_segment_xy(a: tuple[float, float], b: tuple[float, float], p: tuple[float, float], eps: float = 1e-9) -> bool:
    return (
        min(a[0], b[0]) - eps <= p[0] <= max(a[0], b[0]) + eps
        and min(a[1], b[1]) - eps <= p[1] <= max(a[1], b[1]) + eps
    )


def _segments_intersect_xy(a1, a2, b1, b2, eps: float = 1e-9) -> bool:
    o1 = _tri_area2_xy(a1, a2, b1)
    o2 = _tri_area2_xy(a1, a2, b2)
    o3 = _tri_area2_xy(b1, b2, a1)
    o4 = _tri_area2_xy(b1, b2, a2)

    if ((o1 > eps and o2 < -eps) or (o1 < -eps and o2 > eps)) and ((o3 > eps and o4 < -eps) or (o3 < -eps and o4 > eps)):
        return True

    if abs(o1) <= eps and _on_segment_xy(a1, a2, b1, eps):
        return True
    if abs(o2) <= eps and _on_segment_xy(a1, a2, b2, eps):
        return True
    if abs(o3) <= eps and _on_segment_xy(b1, b2, a1, eps):
        return True
    if abs(o4) <= eps and _on_segment_xy(b1, b2, a2, eps):
        return True
    return False


def _triangles_overlap_xy(
    ta: tuple[tuple[float, float], tuple[float, float], tuple[float, float]],
    tb: tuple[tuple[float, float], tuple[float, float], tuple[float, float]],
    eps: float = 1e-9,
) -> bool:
    a_min_x, a_max_x, a_min_y, a_max_y = _tri_bbox_xy(ta)
    b_min_x, b_max_x, b_min_y, b_max_y = _tri_bbox_xy(tb)
    if a_max_x < b_min_x - eps or b_max_x < a_min_x - eps or a_max_y < b_min_y - eps or b_max_y < a_min_y - eps:
        return False

    ea = ((ta[0], ta[1]), (ta[1], ta[2]), (ta[2], ta[0]))
    eb = ((tb[0], tb[1]), (tb[1], tb[2]), (tb[2], tb[0]))
    for sa0, sa1 in ea:
        for sb0, sb1 in eb:
            if _segments_intersect_xy(sa0, sa1, sb0, sb1, eps=eps):
                return True

    if _point_in_tri_xy(ta[0], tb, eps=eps):
        return True
    if _point_in_tri_xy(tb[0], ta, eps=eps):
        return True
    return False


def _object_world_xy_triangles(
    obj: bpy.types.Object,
    min_area: float = 1e-10,
) -> list[tuple[tuple[float, float], tuple[float, float], tuple[float, float]]]:
    if obj is None or obj.type != "MESH" or obj.data is None:
        return []
    mw = obj.matrix_world
    tris: list[tuple[tuple[float, float], tuple[float, float], tuple[float, float]]] = []
    verts = obj.data.vertices
    for poly in obj.data.polygons:
        idx = list(poly.vertices)
        if len(idx) < 3:
            continue
        p0w = mw @ verts[idx[0]].co
        p0 = (float(p0w.x), float(p0w.y))
        for k in range(1, len(idx) - 1):
            p1w = mw @ verts[idx[k]].co
            p2w = mw @ verts[idx[k + 1]].co
            p1 = (float(p1w.x), float(p1w.y))
            p2 = (float(p2w.x), float(p2w.y))
            if abs(_tri_area2_xy(p0, p1, p2)) > min_area:
                tris.append((p0, p1, p2))
    return tris


def exact_mesh_overlap_xy(obj_a: bpy.types.Object, obj_b: bpy.types.Object) -> bool:
    ta = _object_world_xy_triangles(obj_a)
    tb = _object_world_xy_triangles(obj_b)
    if not ta or not tb:
        return False

    bboxes_a = [_tri_bbox_xy(t) for t in ta]
    bboxes_b = [_tri_bbox_xy(t) for t in tb]

    for i, tri_a in enumerate(ta):
        a_min_x, a_max_x, a_min_y, a_max_y = bboxes_a[i]
        for j, tri_b in enumerate(tb):
            b_min_x, b_max_x, b_min_y, b_max_y = bboxes_b[j]
            if a_max_x < b_min_x or b_max_x < a_min_x or a_max_y < b_min_y or b_max_y < a_min_y:
                continue
            if _triangles_overlap_xy(tri_a, tri_b):
                return True
    return False


def relation_2d_with_pad(meta_a: dict, meta_b: dict, pad: float, moved_pos=None) -> str:
    pad = float(pad)

    pos_a = moved_pos if moved_pos is not None else None

    # AABB precheck must use moved_pos
    if not aabb_overlap_xy_by_meta(meta_a, meta_b, inflate=pad, pos_a=pos_a, pos_b=None):
        return "SAFE"

    # Exact overlap: OBB
    if obb_overlap(meta_a, meta_b, inflate=0.0, pos_a=pos_a, pos_b=None):
        return "COLLIDE"
    if obb_overlap(meta_a, meta_b, inflate=pad, pos_a=pos_a, pos_b=None):
        return "NEAR"
    return "SAFE"


def collision_pairs_in_scene(metas: list[dict], pos_overrides: dict = None) -> list[tuple[int, int]]:
    """
    Find colliding pairs in scene.
    pos_overrides: optional dict {idx: (x, y)} to override positions for collision detection.
    """
    if pos_overrides is None:
        pos_overrides = {}
    pairs = []
    n = len(metas)
    for i in range(n):
        for j in range(i + 1, n):
            pos_i = pos_overrides.get(i, None)
            pos_j = pos_overrides.get(j, None)
            if not aabb_overlap_xy_by_meta(metas[i], metas[j], inflate=0.0, pos_a=pos_i, pos_b=pos_j):
                continue
            if obb_overlap(metas[i], metas[j], inflate=0.0, pos_a=pos_i, pos_b=pos_j):
                pairs.append((i + 1, j + 1))
    return pairs


# --------------------------------------------------------------------------------------
# Camera / Labels / Scale marker (match reference behavior)
# --------------------------------------------------------------------------------------
def create_dark_material(name: str) -> bpy.types.Material:
    """Create a dark material (black emission) for scale marker visibility on white background."""
    if name in bpy.data.materials:
        return bpy.data.materials[name]
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()
    out = nodes.new("ShaderNodeOutputMaterial")
    em = nodes.new("ShaderNodeEmission")
    # Black color for visibility on white background
    em.inputs["Color"].default_value = (0.0, 0.0, 0.0, 1.0)
    em.inputs["Strength"].default_value = 1.0
    links.new(em.outputs["Emission"], out.inputs["Surface"])
    return mat


def create_label_material(name: str, strength: float = 3.0) -> bpy.types.Material:
    if name in bpy.data.materials:
        return bpy.data.materials[name]
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()
    out = nodes.new("ShaderNodeOutputMaterial")
    em = nodes.new("ShaderNodeEmission")
    em.inputs["Color"].default_value = (1.0, 1.0, 1.0, 1.0)
    em.inputs["Strength"].default_value = float(strength)
    links.new(em.outputs["Emission"], out.inputs["Surface"])
    return mat


def add_label(obj: bpy.types.Object, label_text: str, cam: bpy.types.Object, font_size: float, z_top: float) -> None:
    # place label at object AABB center xy, and at z_top + padding
    b = world_bounds_from_obj(obj)
    cx, cy = b["center_x"], b["center_y"]

    curve = bpy.data.curves.new(f"Label_{label_text}_curve", type="FONT")
    curve.body = str(label_text)
    curve.size = float(font_size)
    curve.align_x = "CENTER"
    curve.align_y = "CENTER"
    curve.extrude = max(0.02, float(font_size) * 0.02)
    curve.fill_mode = "BOTH"

    t = bpy.data.objects.new(f"Label_{label_text}", curve)
    bpy.context.collection.objects.link(t)
    t.location = (float(cx), float(cy), float(z_top))

    # Billboard to camera
    bb = t.constraints.new(type="LOCKED_TRACK")
    bb.target = cam
    bb.track_axis = "TRACK_Z"
    bb.lock_axis = "LOCK_Y"

    lr = t.constraints.new(type="LIMIT_ROTATION")
    lr.owner_space = "LOCAL"
    lr.use_limit_z = True
    lr.min_z = 0.0
    lr.max_z = 0.0

    t.data.materials.clear()
    t.data.materials.append(create_black_label_material(f"Label_{label_text}_mat"))

    t.hide_render = False
    t.visible_shadow = False
    if hasattr(t, "cycles_visibility"):
        t.cycles_visibility.shadow = False
        t.cycles_visibility.diffuse = False
        t.cycles_visibility.glossy = False
        t.cycles_visibility.ambient_occlusion = False

    bpy.context.view_layer.update()


def rect_overlaps_any_building(rect_min_x, rect_max_x, rect_min_y, rect_max_y, objs, pad: float) -> bool:
    for o in objs:
        b = world_bounds_from_obj(o)
        if not (
            (rect_max_x + pad) < (b["min_x"] - pad) or
            (rect_min_x - pad) > (b["max_x"] + pad) or
            (rect_max_y + pad) < (b["min_y"] - pad) or
            (rect_min_y - pad) > (b["max_y"] + pad)
        ):
            return True
    return False


def pick_scale_marker_position(bounds: dict, building_objs: list[bpy.types.Object]) -> tuple[float, float]:
    """
    Consistent with the reference code: prioritize empty area in the bottom-right corner
    """
    w = SCALE_MARK_LENGTH_UNITS + 1.2
    h = SCALE_TICK_LEN_Y + 1.0

    min_x, max_x = float(bounds["min_x"]), float(bounds["max_x"])
    min_y, max_y = float(bounds["min_y"]), float(bounds["max_y"])

    candidates = [
        (min_x + SCALE_MARK_MARGIN, max_y - SCALE_MARK_MARGIN - h),  # top-left (preferred - inside scene)
        (min_x + SCALE_MARK_MARGIN, min_y + SCALE_MARK_MARGIN),  # bottom-left
        (max_x - SCALE_MARK_MARGIN - w, max_y - SCALE_MARK_MARGIN - h),  # top-right
        (max_x - SCALE_MARK_MARGIN - w, min_y + SCALE_MARK_MARGIN),  # bottom-right
        (min_x + SCALE_MARK_MARGIN, (min_y + max_y) * 0.5 - h * 0.5),
        (max_x - SCALE_MARK_MARGIN - w, (min_y + max_y) * 0.5 - h * 0.5),
    ]

    for (x0, y0) in candidates:
        if not rect_overlaps_any_building(
            x0, x0 + w, y0, y0 + h, building_objs, pad=SCALE_PAD_FOR_PLACEMENT
        ):
            return float(x0), float(y0)

    return float(max_x - SCALE_MARK_MARGIN - w), float(min_y + SCALE_MARK_MARGIN)


def add_scale_marker(bounds: dict, building_objs: list[bpy.types.Object], cam: bpy.types.Object, length_units: float = 1.0) -> None:
    """
    Marker in XY plane, visible in top view:
    - bar along X
    - two ticks extend along Y
    - placed at z = max_z + eps
    """
    x0, y0 = pick_scale_marker_position(bounds, building_objs)
    z = float(bounds["max_z"]) + SCALE_MARK_Z_EPS
    bar_y = y0 + SCALE_TICK_LEN_Y * 0.5

    print(f"[DEBUG] Scale marker position: ({x0:.2f}, {y0:.2f}), z={z:.2f}, bounds={bounds}")

    # Use a black scale marker on transparent backgrounds for visibility
    mat = create_dark_material("Scale_Mark_Mat")

    created = []

    # Bar - create explicitly with correct dimensions from start
    mesh = bpy.data.meshes.new("Scale_Bar_Mesh")
    bar = bpy.data.objects.new("Scale_Bar", mesh)
    bpy.context.collection.objects.link(bar)
    # Create bar geometry: 1 unit long along X, centered at x0 + length_units/2
    bar_verts = [
        (x0, bar_y - SCALE_BAR_THICKNESS/2, z - SCALE_BAR_THICKNESS/2),
        (x0 + length_units, bar_y - SCALE_BAR_THICKNESS/2, z - SCALE_BAR_THICKNESS/2),
        (x0 + length_units, bar_y + SCALE_BAR_THICKNESS/2, z - SCALE_BAR_THICKNESS/2),
        (x0, bar_y + SCALE_BAR_THICKNESS/2, z - SCALE_BAR_THICKNESS/2),
        (x0, bar_y - SCALE_BAR_THICKNESS/2, z + SCALE_BAR_THICKNESS/2),
        (x0 + length_units, bar_y - SCALE_BAR_THICKNESS/2, z + SCALE_BAR_THICKNESS/2),
        (x0 + length_units, bar_y + SCALE_BAR_THICKNESS/2, z + SCALE_BAR_THICKNESS/2),
        (x0, bar_y + SCALE_BAR_THICKNESS/2, z + SCALE_BAR_THICKNESS/2),
    ]
    bar_faces = [(0,1,2,3), (4,5,6,7), (0,1,5,4), (2,3,7,6), (0,3,7,4), (1,2,6,5)]
    mesh.from_pydata(bar_verts, [], bar_faces)
    mesh.update()
    bar.data.materials.append(mat)
    created.append(bar)

    # Left Tick - thinner than main bar
    tick_mesh = bpy.data.meshes.new("Scale_Tick_L_Mesh")
    tick_l = bpy.data.objects.new("Scale_Tick_L", tick_mesh)
    bpy.context.collection.objects.link(tick_l)
    tick_l_verts = [
        (x0 - SCALE_TICK_THICKNESS/2, bar_y - SCALE_TICK_LEN_Y/2, z - SCALE_TICK_THICKNESS/2),
        (x0 + SCALE_TICK_THICKNESS/2, bar_y - SCALE_TICK_LEN_Y/2, z - SCALE_TICK_THICKNESS/2),
        (x0 + SCALE_TICK_THICKNESS/2, bar_y + SCALE_TICK_LEN_Y/2, z - SCALE_TICK_THICKNESS/2),
        (x0 - SCALE_TICK_THICKNESS/2, bar_y + SCALE_TICK_LEN_Y/2, z - SCALE_TICK_THICKNESS/2),
        (x0 - SCALE_TICK_THICKNESS/2, bar_y - SCALE_TICK_LEN_Y/2, z + SCALE_TICK_THICKNESS/2),
        (x0 + SCALE_TICK_THICKNESS/2, bar_y - SCALE_TICK_LEN_Y/2, z + SCALE_TICK_THICKNESS/2),
        (x0 + SCALE_TICK_THICKNESS/2, bar_y + SCALE_TICK_LEN_Y/2, z + SCALE_TICK_THICKNESS/2),
        (x0 - SCALE_TICK_THICKNESS/2, bar_y + SCALE_TICK_LEN_Y/2, z + SCALE_TICK_THICKNESS/2),
    ]
    tick_faces = [(0,1,2,3), (4,5,6,7), (0,1,5,4), (2,3,7,6), (0,3,7,4), (1,2,6,5)]
    tick_mesh.from_pydata(tick_l_verts, [], tick_faces)
    tick_mesh.update()
    tick_l.data.materials.append(mat)
    created.append(tick_l)

    # Right Tick - thinner than main bar
    tick_r_mesh = bpy.data.meshes.new("Scale_Tick_R_Mesh")
    tick_r = bpy.data.objects.new("Scale_Tick_R", tick_r_mesh)
    bpy.context.collection.objects.link(tick_r)
    x_r = x0 + length_units
    tick_r_verts = [
        (x_r - SCALE_TICK_THICKNESS/2, bar_y - SCALE_TICK_LEN_Y/2, z - SCALE_TICK_THICKNESS/2),
        (x_r + SCALE_TICK_THICKNESS/2, bar_y - SCALE_TICK_LEN_Y/2, z - SCALE_TICK_THICKNESS/2),
        (x_r + SCALE_TICK_THICKNESS/2, bar_y + SCALE_TICK_LEN_Y/2, z - SCALE_TICK_THICKNESS/2),
        (x_r - SCALE_TICK_THICKNESS/2, bar_y + SCALE_TICK_LEN_Y/2, z - SCALE_TICK_THICKNESS/2),
        (x_r - SCALE_TICK_THICKNESS/2, bar_y - SCALE_TICK_LEN_Y/2, z + SCALE_TICK_THICKNESS/2),
        (x_r + SCALE_TICK_THICKNESS/2, bar_y - SCALE_TICK_LEN_Y/2, z + SCALE_TICK_THICKNESS/2),
        (x_r + SCALE_TICK_THICKNESS/2, bar_y + SCALE_TICK_LEN_Y/2, z + SCALE_TICK_THICKNESS/2),
        (x_r - SCALE_TICK_THICKNESS/2, bar_y + SCALE_TICK_LEN_Y/2, z + SCALE_TICK_THICKNESS/2),
    ]
    tick_r_faces = [(0,1,2,3), (4,5,6,7), (0,1,5,4), (2,3,7,6), (0,3,7,4), (1,2,6,5)]
    tick_r_mesh.from_pydata(tick_r_verts, [], tick_r_faces)
    tick_r_mesh.update()
    tick_r.data.materials.append(mat)
    created.append(tick_r)

    print(f"[DEBUG] Created {len(created)} scale marker objects")

    # Disable shadows & ensure render visible
    for o in created:
        o.hide_render = False
        o.visible_shadow = False
        if hasattr(o, "cycles_visibility"):
            o.cycles_visibility.shadow = False
            o.cycles_visibility.diffuse = False
            o.cycles_visibility.glossy = False
            o.cycles_visibility.ambient_occlusion = False

    # Label - always show "1 unit" as the reference scale
    curve = bpy.data.curves.new("Scale_Label_curve", type="FONT")
    curve.body = "1 unit"
    curve.size = float(SCALE_LABEL_SIZE)
    curve.align_x = "LEFT"
    curve.align_y = "CENTER"
    curve.extrude = 0.2  # Thicker for bold look
    curve.fill_mode = "BOTH"

    text_obj = bpy.data.objects.new("Scale_Label", curve)
    bpy.context.collection.objects.link(text_obj)
    text_obj.location = (float(x0 + length_units + 4.0), float(bar_y), float(z + SCALE_LABEL_Z_OFF))
    text_obj.data.materials.clear()
    text_obj.data.materials.append(create_dark_material("Scale_Label_Mat"))

    bb = text_obj.constraints.new(type="LOCKED_TRACK")
    bb.target = cam
    bb.track_axis = "TRACK_Z"
    bb.lock_axis = "LOCK_Y"

    lr = text_obj.constraints.new(type="LIMIT_ROTATION")
    lr.owner_space = "LOCAL"
    lr.use_limit_z = True
    lr.min_z = 0.0
    lr.max_z = 0.0

    text_obj.hide_render = False
    text_obj.visible_shadow = False
    if hasattr(text_obj, "cycles_visibility"):
        text_obj.cycles_visibility.shadow = False
        text_obj.cycles_visibility.diffuse = False
        text_obj.cycles_visibility.glossy = False
        text_obj.cycles_visibility.ambient_occlusion = False

    bpy.context.view_layer.update()


def render_view(
    cam: bpy.types.Object,
    output_path: str,
    add_north: bool = True,
    north_world_dir: Vector = Vector((0.0, 1.0, 0.0)),
    add_unit_bar: bool = False,
) -> None:
    scene = bpy.context.scene
    scene.camera = cam
    scene.render.filepath = output_path
    bpy.ops.render.render(write_still=True)
    if add_north:
        reframe_image_focus_buildings(
            output_path,
            arrow_size=TOP_NORTH_ARROW_SIZE,
            reserve_for_north=True,
            building_bbox=None,
        )
        draw_north_arrow(
            output_path,
            cam=cam,
            north_world_dir=north_world_dir,
            arrow_size=TOP_NORTH_ARROW_SIZE,
            corner_idx=None,
            add_unit_bar=add_unit_bar,
        )
        trim_image_to_alpha_bbox(output_path, pad_px=FINAL_TRIM_PAD_PX)


def render_ref_top(
    cam: bpy.types.Object,
    output_path: str,
    bounds: dict,
    building_objs: list[bpy.types.Object],
    id_to_obj: dict[int, bpy.types.Object],
    with_scale_marker: bool,
    label_font_size: float,
    region_max_dim: float,
) -> None:
    clear_labels_only()
    clear_overlays_only()

    z_top = float(bounds["max_z"]) + float(region_max_dim) * LABEL_Z_PAD_RATIO
    for idx in sorted(id_to_obj.keys()):
        add_label(id_to_obj[idx], str(idx), cam, font_size=label_font_size, z_top=z_top)

    bpy.context.view_layer.update()
    _ = with_scale_marker  # legacy arg; scale bar is now always in north panel
    render_view(cam, output_path, add_unit_bar=True)


# --------------------------------------------------------------------------------------
# QA tasks
# --------------------------------------------------------------------------------------
def _move_dir_to_vec(d: str) -> tuple[float, float]:
    return {"E": (1.0, 0.0), "W": (-1.0, 0.0), "N": (0.0, 1.0), "S": (0.0, -1.0)}[d]


def _move_dir_to_words_en(d: str) -> str:
    return {"E": "East", "W": "West", "N": "North", "S": "South"}[d]


def _abs_images(sample_dir: str, names: list[str]) -> list[str]:
    return [os.path.abspath(os.path.join(sample_dir, n)) for n in names]


def qa_task_move_collision_yesno(sample_dir: str, move_id: int, other_id: int, dir_token: str, dist_units: int, will_collide: bool) -> dict:
    dir_en = _move_dir_to_words_en(dir_token)
    q = (
        "There is one image: a top-view image.\n"
        "Directions in the image: North=up, South=down, East=right, West=left.\n"
        f"If building {move_id} is moved {dir_en} by {dist_units} units, "
        f"will it overlap (collide) with building {other_id}? Answer with Yes or No.\n\n"
        "Top-view image: <image>\n"
        "Note: the image includes a 1 unit scale bar.\n"
    )
    return {
        "question": q,
        "answer": "Yes" if will_collide else "No",
        "images": _abs_images(sample_dir, ["top_move.png"]),
        "task_type": "top_move_overlap",
        "meta": {
            "move_id": move_id,
            "other_id": other_id,
            "direction": dir_en,
            "dist_units": int(dist_units),
            "mapping": {"North": "up", "South": "down", "East": "right", "West": "left"},
            "adjacent": "nearest_neighbor",
        },
    }


def qa_task_swap_collision_yesno(sample_dir: str, a_id: int, b_id: int, before_collide: bool, after_collide: bool) -> dict:
    q = (
        "There is one image: a top-view image.\n"
        f"If we swap the positions of building {a_id} and building {b_id}, "
        "will there be any building-to-building overlap (collision) in the scene AFTER the swap? Answer with Yes or No.\n\n"
        "Top-view image: <image>"
    )
    return {
        "question": q,
        "answer": "Yes" if after_collide else "No",
        "images": _abs_images(sample_dir, ["top_swap.png"]),
        "task_type": "top_swap_overlap",
        "meta": {
            "swap_a": a_id,
            "swap_b": b_id,
            "before_collide": before_collide,
            "after_collide": after_collide,
            "case": "collide_to_safe" if (before_collide and not after_collide) else "safe_to_collide",
            "collision_mode": "2D_footprint_AABB_precheck",
        },
    }


# --------------------------------------------------------------------------------------
# Region data IO
# --------------------------------------------------------------------------------------
def load_region_data(region_file_or_dir: str) -> dict:
    if os.path.isdir(region_file_or_dir):
        p = os.path.join(region_file_or_dir, "region_data.json")
    else:
        p = region_file_or_dir
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f)


def _load_failed_region_ids(failed_regions_path: str) -> set[int]:
    if not os.path.exists(failed_regions_path):
        return set()
    try:
        with open(failed_regions_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, list):
            return {int(x) for x in data}
    except Exception as e:
        print(f"[WARN] Failed to read failed_regions: {failed_regions_path}, err={e}")
    return set()


def resolve_region_inputs(blend_path: str, region_dir: str, use_clean: bool) -> tuple[str, str, set[int], bool]:
    clean_blend_path = os.environ.get("CLEAN_BLEND_PATH", blend_path.replace(".blend", "_clean.blend"))
    clean_region_json_path = os.environ.get("CLEAN_REGION_JSON_PATH", os.path.join(region_dir, "region_data_clean.json"))
    raw_region_json_path = os.path.join(region_dir, "region_data.json")
    failed_regions_path = os.environ.get("FAILED_REGIONS_PATH", os.path.join(region_dir, "failed_regions.json"))

    failed_region_ids = _load_failed_region_ids(failed_regions_path)

    if use_clean and os.path.exists(clean_blend_path) and os.path.exists(clean_region_json_path):
        return clean_blend_path, clean_region_json_path, failed_region_ids, True

    if use_clean:
        missing = []
        if not os.path.exists(clean_blend_path):
            missing.append(clean_blend_path)
        if not os.path.exists(clean_region_json_path):
            missing.append(clean_region_json_path)
        print("[WARN] Incomplete clean inputs; falling back to raw scene. Missing files:")
        for p in missing:
            print(f"       - {p}")

    return blend_path, raw_region_json_path, failed_region_ids, False


# --------------------------------------------------------------------------------------
# Main region pipeline
# --------------------------------------------------------------------------------------
def in_bounds_center(x: float, y: float, bounds: dict, margin: float = 0.5) -> bool:
    return (
        (bounds["min_x"] + margin) <= x <= (bounds["max_x"] - margin) and
        (bounds["min_y"] + margin) <= y <= (bounds["max_y"] - margin)
    )


def nearest_neighbor_id(ids: list[int], metas: list[dict], pivot_id: int) -> int:
    px, py = metas[pivot_id - 1]["pos"]
    best = None
    best_d = 1e30
    for i in ids:
        if i == pivot_id:
            continue
        qx, qy = metas[i - 1]["pos"]
        d = (px - qx) ** 2 + (py - qy) ** 2
        if d < best_d:
            best_d = d
            best = i
    return int(best) if best is not None else int(random.choice([i for i in ids if i != pivot_id]))


def process_region(
    region_id: int,
    region: dict,
    labeler: BuildingLabeler,
    sample_idx: int,
    variant_idx: int = 1,
    variant_total: int = 1,
) -> dict | None:
    building_ids = region["building_ids"]
    objs = []
    id_to_obj = {}

    # Collect objects in blender
    for i, bid in enumerate(building_ids):
        o = bpy.data.objects.get(bid)
        if o and o.type == "MESH":
            objs.append(o)
            id_to_obj[i + 1] = o

    if len(objs) > MAX_BUILDINGS_PER_REGION:
        print(
            f"[Region {region_id}] skip: {len(objs)} mesh buildings exceed limit {MAX_BUILDINGS_PER_REGION}"
        )
        return None

    if len(objs) < 3:
        print(f"[Region {region_id}] skip: only {len(objs)} mesh buildings")
        return None

    # Ensure these objects are movable by location (bake if needed)
    ensure_buildings_movable(objs)

    # Build metas from actual objects
    metas = []
    for i in range(len(objs)):
        metas.append(build_meta_from_obj(objs[i], label_id=i + 1))

    # Bounds
    bounds = compute_scene_bounds(objs)
    region_max_dim = max(bounds["width"], bounds["depth"])
    label_font_size = float(region_max_dim) * LABEL_SIZE_RATIO

    # Setup region visibility/masks/roads with labeler
    labeler.set_region_visibility(building_ids)
    set_road_visibility(SHOW_ROADS_IN_REGION_RENDER)
    labeler.clear_mask_materials()
    labeler.clear_all_labels()
    apply_white_film_to_buildings(building_ids)
    if SHOW_ROADS_IN_REGION_RENDER:
        apply_road_material()

    cam_top = labeler.setup_camera_top_down(bounds, "Camera_Top")
    fit_ortho_camera_to_objects(
        cam_top,
        objs,
        margin_ratio=TOP_FIT_MARGIN_RATIO,
        min_ortho_scale=MIN_FIT_ORTHO_SCALE,
    )

    # Output dirs
    if int(variant_total) > 1:
        sample_dir = os.path.join(OUTPUT_DIR, f"region_{region_id:03d}_v{int(variant_idx):02d}")
    else:
        sample_dir = os.path.join(OUTPUT_DIR, f"region_{region_id:03d}")
    os.makedirs(sample_dir, exist_ok=True)
    ref_dir = os.path.join(sample_dir, "ref_images")
    os.makedirs(ref_dir, exist_ok=True)

    ids = list(range(1, len(objs) + 1))

    def _with_center_overrides(pos_overrides: dict[int, tuple[float, float]] | None, fn):
        if not pos_overrides:
            return fn()
        saved = {}
        try:
            for idx, new_center in pos_overrides.items():
                if idx < 0 or idx >= len(objs):
                    continue
                obj = objs[idx]
                saved[idx] = obj.location.copy()
                old_cx, old_cy = metas[idx]["obb"]["center"][:2]
                dx = float(new_center[0] - old_cx)
                dy = float(new_center[1] - old_cy)
                obj.location = (float(obj.location.x + dx), float(obj.location.y + dy), float(obj.location.z))
            bpy.context.view_layer.update()
            return fn()
        finally:
            for idx, loc in saved.items():
                objs[idx].location = loc
            if saved:
                bpy.context.view_layer.update()

    def _exact_pair_collide(idx_a: int, idx_b: int, pos_overrides: dict[int, tuple[float, float]] | None = None) -> bool:
        pos_a = pos_overrides.get(idx_a) if pos_overrides else None
        pos_b = pos_overrides.get(idx_b) if pos_overrides else None

        def _calc() -> bool:
            if not aabb_overlap_xy_by_meta(metas[idx_a], metas[idx_b], inflate=0.0, pos_a=pos_a, pos_b=pos_b):
                return False
            return exact_mesh_overlap_xy(objs[idx_a], objs[idx_b])

        return bool(_with_center_overrides(pos_overrides, _calc))

    def _exact_scene_collision_pairs(pos_overrides: dict[int, tuple[float, float]] | None = None) -> list[tuple[int, int]]:
        def _calc() -> list[tuple[int, int]]:
            pairs = []
            n = len(metas)
            for i in range(n):
                for j in range(i + 1, n):
                    pos_i = pos_overrides.get(i) if pos_overrides else None
                    pos_j = pos_overrides.get(j) if pos_overrides else None
                    if not aabb_overlap_xy_by_meta(metas[i], metas[j], inflate=0.0, pos_a=pos_i, pos_b=pos_j):
                        continue
                    if exact_mesh_overlap_xy(objs[i], objs[j]):
                        pairs.append((i + 1, j + 1))
            return pairs

        return _with_center_overrides(pos_overrides, _calc)

    # ----------------------------------------------------------
    # QA1 move (strict -> flip)
    # ----------------------------------------------------------
    desired_move_collide = (sample_idx % 2 == 0)
    move_task = None
    move_ref = None  # (move_id, nx, ny)

    def _pick_move(mode: str):
        for _ in range(MOVE_TASK_TRIES):
            move_id = random.choice(ids)
            other_id = nearest_neighbor_id(ids, metas, move_id)

            meta_m = metas[move_id - 1]
            meta_o = metas[other_id - 1]
            old_x, old_y = meta_m["obb"]["center"][:2]
            before_rel = relation_2d_with_pad(meta_m, meta_o, pad=COLLISION_PAD, moved_pos=None)
            if before_rel == "NEAR":
                continue
            before_collide_fast = (before_rel == "COLLIDE")

            dirs = MOVE_DIR_POOL[:]
            dists = MOVE_DIST_POOL[:]
            random.shuffle(dirs)
            random.shuffle(dists)

            for d in dirs:
                vx, vy = _move_dir_to_vec(d)
                for dist in dists:
                    actual_dist = dist * UNIT_SCALE
                    nx = float(old_x + vx * actual_dist)
                    ny = float(old_y + vy * actual_dist)
                    if not in_bounds_center(nx, ny, bounds, margin=IN_BOUNDS_MARGIN):
                        continue

                    rel = relation_2d_with_pad(meta_m, meta_o, pad=COLLISION_PAD, moved_pos=(nx, ny))
                    if rel == "NEAR":
                        continue
                    after_collide_fast = (rel == "COLLIDE")

                    if mode == "strict":
                        if after_collide_fast != desired_move_collide:
                            continue
                    elif mode == "flip":
                        if after_collide_fast == before_collide_fast:
                            continue
                    else:
                        continue

                    move_idx = move_id - 1
                    other_idx = other_id - 1
                    pos_overrides = {move_idx: (nx, ny)}
                    before_collide_exact = _exact_pair_collide(move_idx, other_idx, pos_overrides=None)
                    after_collide_exact = _exact_pair_collide(move_idx, other_idx, pos_overrides=pos_overrides)

                    # Final exact check before persisting answer; mismatch -> keep searching.
                    if after_collide_exact != after_collide_fast:
                        continue
                    if before_collide_exact != before_collide_fast:
                        continue

                    if mode == "strict":
                        if after_collide_exact != desired_move_collide:
                            continue
                    elif mode == "flip":
                        if after_collide_exact == before_collide_exact:
                            continue
                    else:
                        continue

                    task = qa_task_move_collision_yesno(sample_dir, move_id, other_id, d, int(dist), after_collide_exact)
                    return task, (move_id, nx, ny)

        return None, None

    move_task, move_ref = _pick_move("strict")
    if move_task is None:
        move_task, move_ref = _pick_move("flip")

    # ----------------------------------------------------------
    # QA2 swap (alternate desired_after_collide)
    # ----------------------------------------------------------
    desired_after_collide = (sample_idx % 2 == 1)

    before_pairs = collision_pairs_in_scene(metas)
    before_collide_fast = (len(before_pairs) > 0)
    before_pairs_exact = _exact_scene_collision_pairs()
    before_collide = (len(before_pairs_exact) > 0)

    swap_task = None
    swap_ref = None  # (a_id, b_id)

    all_pairs = list(combinations(ids, 2))
    random.shuffle(all_pairs)

    def _pick_swap(mode: str):
        for a_id, b_id in all_pairs:
            pa = tuple(metas[a_id - 1]["obb"]["center"][:2])
            pb = tuple(metas[b_id - 1]["obb"]["center"][:2])

            pos_overrides = {
                a_id - 1: pb,
                b_id - 1: pa,
            }

            after_pairs = collision_pairs_in_scene(metas, pos_overrides=pos_overrides)
            after_collide_fast = (len(after_pairs) > 0)

            if mode == "strict":
                if after_collide_fast != desired_after_collide:
                    continue
                if before_collide_fast and not after_collide_fast:
                    involved_before = any(a_id in pair or b_id in pair for pair in before_pairs)
                    if not involved_before:
                        continue
                elif not before_collide_fast and after_collide_fast:
                    involved_after = any(a_id in pair or b_id in pair for pair in after_pairs)
                    if not involved_after:
                        continue
            elif mode == "flip":
                if after_collide_fast == before_collide_fast:
                    continue
            else:
                continue

            after_pairs_exact = _exact_scene_collision_pairs(pos_overrides=pos_overrides)
            after_collide_exact = (len(after_pairs_exact) > 0)

            # Final exact check before persisting answer; mismatch -> keep searching.
            if after_collide_exact != after_collide_fast:
                continue

            if mode == "strict":
                if after_collide_exact != desired_after_collide:
                    continue
                if before_collide and not after_collide_exact:
                    involved_before_exact = any(a_id in pair or b_id in pair for pair in before_pairs_exact)
                    if not involved_before_exact:
                        continue
                elif not before_collide and after_collide_exact:
                    involved_after_exact = any(a_id in pair or b_id in pair for pair in after_pairs_exact)
                    if not involved_after_exact:
                        continue
            elif mode == "flip":
                if after_collide_exact == before_collide:
                    continue
            else:
                continue

            task = qa_task_swap_collision_yesno(sample_dir, a_id, b_id, before_collide, after_collide_exact)
            return task, (a_id, b_id)
        return None, None

    swap_task, swap_ref = _pick_swap("strict")
    if swap_task is None:
        swap_task, swap_ref = _pick_swap("flip")

    # If both failed, skip region
    if move_task is None and swap_task is None:
        print(f"[Region {region_id}] failed: no tasks generated")
        labeler.clear_all_labels()
        labeler.clear_mask_materials()
        labeler.show_all_visible_objects()
        return None

    # ----------------------------------------------------------
    # Render top_swap.png (north panel includes 1-unit scale bar)
    # ----------------------------------------------------------
    render_ref_top(
        cam=cam_top,
        output_path=os.path.join(sample_dir, "top_swap.png"),
        bounds=bounds,
        building_objs=objs,
        id_to_obj=id_to_obj,
        with_scale_marker=False,
        label_font_size=label_font_size,
        region_max_dim=region_max_dim,
    )

    # Render top_move.png (north panel includes 1-unit scale bar)
    render_ref_top(
        cam=cam_top,
        output_path=os.path.join(sample_dir, "top_move.png"),
        bounds=bounds,
        building_objs=objs,
        id_to_obj=id_to_obj,
        with_scale_marker=True,
        label_font_size=label_font_size,
        region_max_dim=region_max_dim,
    )

    # ----------------------------------------------------------
    # Render QA1 move after (north panel includes 1-unit scale bar)
    # ----------------------------------------------------------
    if move_ref is not None:
        m_id, nx, ny = move_ref
        obj_m = id_to_obj[m_id]
        old_loc = obj_m.location.copy()
        # Get the OBB center from meta for correct delta calculation
        meta_m = metas[m_id - 1]
        obb_center_x, obb_center_y = meta_m["obb"]["center"][:2]
        # Calculate delta: where we want OBB to be minus where it currently is
        delta_x = float(nx - obb_center_x)
        delta_y = float(ny - obb_center_y)
        try:
            # Apply delta to object's actual location
            obj_m.location = (float(old_loc.x + delta_x), float(old_loc.y + delta_y), float(old_loc.z))
            bpy.context.view_layer.update()

            # Recompute bounds based on moved object positions
            new_bounds = compute_scene_bounds(objs)
            new_region_max_dim = max(new_bounds["width"], new_bounds["depth"])
            new_label_font_size = float(new_region_max_dim) * LABEL_SIZE_RATIO

            render_ref_top(
                cam=cam_top,
                output_path=os.path.join(ref_dir, "qa1_move_after.png"),
                bounds=new_bounds,
                building_objs=objs,
                id_to_obj=id_to_obj,
                with_scale_marker=True,
                label_font_size=new_label_font_size,
                region_max_dim=new_region_max_dim,
            )
        finally:
            obj_m.location = old_loc
            bpy.context.view_layer.update()

    # ----------------------------------------------------------
    # Render QA2 swap after (north panel includes 1-unit scale bar)
    # ----------------------------------------------------------
    if swap_ref is not None:
        a_id, b_id = swap_ref
        obj_a = id_to_obj[a_id]
        obj_b = id_to_obj[b_id]
        loc_a = obj_a.location.copy()
        loc_b = obj_b.location.copy()

        # Get OBB centers for correct delta calculation
        meta_a = metas[a_id - 1]
        meta_b = metas[b_id - 1]
        obb_a = meta_a["obb"]["center"][:2]
        obb_b = meta_b["obb"]["center"][:2]

        # Calculate deltas: where we want each OBB to be
        # For swap: a should go to b's position, b should go to a's position
        delta_a_x = obb_b[0] - obb_a[0]  # b's pos - a's pos
        delta_a_y = obb_b[1] - obb_a[1]
        delta_b_x = obb_a[0] - obb_b[0]  # a's pos - b's pos
        delta_b_y = obb_a[1] - obb_b[1]

        try:
            # Apply deltas to object locations
            obj_a.location = (float(loc_a.x + delta_a_x), float(loc_a.y + delta_a_y), float(loc_a.z))
            obj_b.location = (float(loc_b.x + delta_b_x), float(loc_b.y + delta_b_y), float(loc_b.z))
            bpy.context.view_layer.update()

            # Recompute bounds based on swapped object positions
            new_bounds = compute_scene_bounds(objs)
            new_region_max_dim = max(new_bounds["width"], new_bounds["depth"])
            new_label_font_size = float(new_region_max_dim) * LABEL_SIZE_RATIO

            render_ref_top(
                cam=cam_top,
                output_path=os.path.join(ref_dir, "qa2_swap_after.png"),
                bounds=new_bounds,
                building_objs=objs,
                id_to_obj=id_to_obj,
                with_scale_marker=False,  # legacy arg; scale bar is in north panel
                label_font_size=new_label_font_size,
                region_max_dim=new_region_max_dim,
            )
        finally:
            obj_a.location = loc_a
            obj_b.location = loc_b
            bpy.context.view_layer.update()

    # Cleanup visibility
    labeler.clear_all_labels()
    labeler.clear_mask_materials()
    labeler.show_all_visible_objects()

    # Collect images
    images = {
        "top_swap": os.path.abspath(os.path.join(sample_dir, "top_swap.png")),
        "top_move": os.path.abspath(os.path.join(sample_dir, "top_move.png")),
    }
    if move_ref is not None:
        images["qa1_move_after"] = os.path.abspath(os.path.join(ref_dir, "qa1_move_after.png"))
    if swap_ref is not None:
        images["qa2_swap_after"] = os.path.abspath(os.path.join(ref_dir, "qa2_swap_after.png"))

    qa_tasks = [t for t in [move_task, swap_task] if t is not None]

    return {
        "region_id": int(region_id),
        "sample_index": int(sample_idx),
        "attempt": int(max(0, variant_idx - 1)),
        "variant_index": int(variant_idx),
        "variant_total": int(variant_total),
        "bounds": bounds,
        "building_count": len(objs),
        "buildings": metas,  # metas include obb
        "images": images,
        "qa": {"top": qa_tasks},
        "special_refs": {
            "scale_marker_units": SCALE_MARK_LENGTH_UNITS,
            "scale_marker_in_north_panel": True,
            "qa1_move_adjacent_pair": True,
            "qa1_balanced_collide": desired_move_collide,
            "qa2_state_flip": True,
            "qa2_desired_before": before_collide,
            "qa2_desired_after": desired_after_collide,
            "qa2_collision_mode": "AABB/OBB_candidate_search+exact_mesh_projection_final_check",
        },
        "camera_params": {
            "top": {"ortho_scale": cam_top.data.ortho_scale, "location": tuple(cam_top.location)},
        },
    }


# --------------------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------------------
def main():
    use_clean = USE_CLEAN_ARG == 1
    if "USE_CLEAN_SCENE" in os.environ:
        use_clean = os.environ.get("USE_CLEAN_SCENE", "1").lower() in ("1", "true", "yes")

    effective_blend_path, effective_region_json_path, failed_region_ids, using_clean = resolve_region_inputs(
        BLEND_PATH,
        REGION_DIR,
        use_clean=use_clean,
    )

    print("=" * 60)
    print(f"[RUN] region={REGION_NAME}")
    print(f"[BLEND] {effective_blend_path}")
    print(f"[REGION_DIR] {REGION_DIR}")
    print(f"[REGION_JSON] {effective_region_json_path}")
    print(f"[USING_CLEAN] {using_clean}")
    print(f"[OUT] {OUTPUT_DIR}")
    print("=" * 60)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Load region json
    region_data = load_region_data(effective_region_json_path)
    regions = region_data.get("regions", [])
    raw_region_count = len(regions)
    if failed_region_ids:
        regions = [r for r in regions if int(r.get("region_id", -1)) not in failed_region_ids]
        print(f"[INFO] after failed-region filter: {len(regions)}/{raw_region_count}")
    if MAX_REGIONS > 0:
        regions = regions[:MAX_REGIONS]
    print(f"[INFO] regions={len(regions)}")

    # Open blend once
    bpy.ops.wm.open_mainfile(filepath=effective_blend_path)
    render_resolution = (RESOLUTION, RESOLUTION) if RESOLUTION > 0 else _render_resolution_px()

    # Render settings
    setup_render(render_resolution)
    force_disable_all_shadows_and_world()

    # Labeler for camera + masking
    labeler = BuildingLabeler(
        region_data_path=effective_region_json_path,
        blend_path=effective_blend_path,
        output_dir=OUTPUT_DIR,
        ortho_scale_factor=1.1,  # Match blender_apply_final_all_regions.py
        label_height_ratio=0.01,
        font_size_ratio=0.07,
        samples=32,
        resolution=render_resolution,
        mask_alpha=0.8,
    )
    # patch lighting to no-shadow
    def _patched_setup_lighting(self):
        scene = bpy.context.scene
        for obj in list(bpy.data.objects):
            if obj.type == "LIGHT":
                bpy.data.objects.remove(obj)

        sun = bpy.data.objects.new("Sun", bpy.data.lights.new("SunLight", type="SUN"))
        bpy.context.collection.objects.link(sun)
        sun.data.energy = 4.0
        sun.rotation_euler = (math.radians(45), math.radians(15), math.radians(30))
        if hasattr(sun.data, "use_shadow"):
            sun.data.use_shadow = False

        fill = bpy.data.objects.new("FillLight", bpy.data.lights.new("FillLight", type="AREA"))
        bpy.context.collection.objects.link(fill)
        fill.data.energy = 150.0
        fill.location = (0.0, 0.0, 100.0)
        fill.data.size = 100.0
        if hasattr(fill.data, "use_shadow"):
            fill.data.use_shadow = False

        scene.cycles.use_shadows = False
        scene.cycles.blur_shadow = 0
        for o in bpy.data.objects:
            if hasattr(o, "cycles_visibility"):
                o.cycles_visibility.cast_shadow = False
                o.cycles_visibility.receive_shadow = False

    labeler.setup_lighting = _patched_setup_lighting.__get__(labeler, BuildingLabeler)
    labeler.setup_render()
    labeler.setup_lighting()

    all_results = []
    ok = 0
    for idx, r in enumerate(regions):
        rid = r.get("region_id", idx)
        print(f"\n[PROCESS] region_id={rid} idx={idx}")
        region_ok = 0
        for variant_idx in range(1, int(QA_PAIRS_PER_REGION) + 1):
            global_sample_idx = idx * int(QA_PAIRS_PER_REGION) + (variant_idx - 1)
            res = process_region(
                rid,
                r,
                labeler,
                global_sample_idx,
                variant_idx=variant_idx,
                variant_total=int(QA_PAIRS_PER_REGION),
            )
            if res is not None:
                all_results.append(res)
                ok += 1
                region_ok += 1
        if int(QA_PAIRS_PER_REGION) > 1:
            print(f"[PROCESS] region_id={rid}: variants ok={region_ok}/{int(QA_PAIRS_PER_REGION)}")

    meta_path = os.path.join(OUTPUT_DIR, "metadata_regions.json")
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2)

    print("\nDONE")
    total_attempts = len(regions) * int(QA_PAIRS_PER_REGION)
    print(f"  ok={ok}/{total_attempts} (variants_per_region={int(QA_PAIRS_PER_REGION)})")
    print(f"  out={OUTPUT_DIR}")
    print(f"  meta={meta_path}")


if __name__ == "__main__":
    main()
